/* ================================================================ planning
   Planning & Goals. Six sections, from the concept groups the ten sets share.  */
var CH = {};
CH.plan = {n:5, title:"Planning & Goals", short:"Planning",
 notes:[
  {id:"plan-polc", h:"Planning and the Four Functions", body:
   '<div class="point"><b>The point</b><p>Management is four functions — <b>planning, organizing, leading, controlling</b> — and <b>planning is the most fundamental</b>, because the other three exist to carry out what was planned. Planning means <b>setting goals and deciding how to achieve them</b>, and it begins from the organization&rsquo;s mission.</p><p class="able"><b>Be able to</b> name the four functions, define planning, say why it comes first, and tell a goal from a plan.</p></div>'+
   '<p class="knowline"><span class="know">In five of the ten sets</span></p>'+
   '<div class="boxrow four"><div class="box"><h4>Planning</h4><p>Set goals and decide how to achieve them.</p></div><div class="box"><h4>Organizing</h4><p>Arrange tasks, people and resources to do the work.</p></div><div class="box"><h4>Leading</h4><p>Motivate, direct and influence people to work toward the goals.</p></div><div class="box"><h4>Controlling</h4><p>Monitor performance, compare it with the goals, and correct as needed.</p></div></div>'+
   '<ul><li><b>Planning</b> is <b>setting objectives and deciding how to reach them</b> — coping with uncertainty by formulating future courses of action.</li>'+
   '<li>It is the <b>most fundamental</b> function: organizing, leading and controlling all follow from it.</li>'+
   '<li>The <b>planning/control cycle</b>: make the plan, carry it out, control the direction by comparing results with the plan, then correct — either by fixing the deviation or by changing the plan.</li>'+
   '<li>Planning starts from the <b>mission</b> — the foundation from which all other planning comes.</li></ul>'+
   '<h3 class="sub" id="plan-goalsplans">Goals versus plans</h3>'+
   '<p>A <b>goal</b> (or objective) is a specific commitment to achieve a measurable result within a stated period — a <b>future end</b>. A <b>plan</b> is the document that outlines how the goal will be achieved — <b>today&rsquo;s means</b>. Goals say <i>what</i>; plans say <i>how</i>.</p>'+
   '<div class="exam-tip"><b>A set gets this wrong</b>One Quizlet answers &ldquo;the foundation all other planning comes from&rdquo; with <i>goals</i>. The usual answer is the <b>mission</b> — goals are derived from it, not the other way round.</div>'+
   '<h3 class="sub" id="plan-process">The organizational planning process</h3>'+
   '<div class="flow"><div class="step"><b>1 &middot; Develop the plan</b>Mission, vision, values and goals.</div><div class="step"><b>2 &middot; Translate the plan</b>Strategy maps, action plans, contingency plans.</div><div class="step"><b>3 &middot; Plan operations</b>Department and unit goals &mdash; SMART goals, MBO.</div><div class="step"><b>4 &middot; Execute the plan</b>Carry it out and manage performance against it.</div><div class="step"><b>5 &middot; Monitor and learn</b>Review the results, compare, correct.</div></div>'+
   '<div class="exam-tip"><b>The sets disagree on step 4</b>One Quizlet calls it <i>execute the plan</i>; another calls it <i>performance management</i>. It is the same step &mdash; carry the plan out and manage performance against it. Give whichever your textbook uses.</div>'},

  {id:"plan-mission", h:"Mission, Vision and Values", body:
   '<div class="point"><b>The point</b><p>Three statements sit at the top of planning. The <b>mission</b> says <b>why the organization exists</b> — its purpose, what it does and whom it serves. The <b>vision</b> says <b>what it wants to become</b> — a long-term direction. <b>Values</b> say how it will behave on the way.</p><p class="able"><b>Be able to</b> define each statement, tell mission from vision, and say what a good mission statement does for people.</p></div>'+
   '<p class="knowline"><span class="know">In seven of the ten sets — the most-covered concept on the page</span></p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Statement</th><th>Answers</th><th>What it contains</th></tr></thead><tbody>'+
   '<tr><td class="head">Mission</td><td class="sm"><b>Why do we exist?</b></td><td class="sm">The organization&rsquo;s purpose or reason for being: its basic product or service, its purpose, and what it does. When a question offers those three and &ldquo;all of the above,&rdquo; it is all of the above.</td></tr>'+
   '<tr><td class="head">Vision</td><td class="sm"><b>What do we want to become?</b></td><td class="sm">A long-term goal describing the future — clear and compelling, meant to inspire.</td></tr>'+
   '<tr><td class="head">Values</td><td class="sm"><b>How will we behave?</b></td><td class="sm">The core priorities and beliefs the organization commits to.</td></tr>'+
   '</tbody></table></div>'+
   '<p>A well-designed mission statement <b>raises motivation and performance</b>: people work harder for a purpose they understand. And the mission is the <b>foundation</b> — the vision, goals and plans are all derived from it.</p>'},

  {id:"plan-levels", h:"Levels of Goals and Plans", body:
   '<div class="point"><b>The point</b><p>Goals and plans cascade down three levels of management, each shorter in range and narrower in scope than the one above. <b>Strategic</b> is the whole organization over years; <b>tactical</b> is a department over months; <b>operational</b> is a unit over weeks. Which manager, which scope, which time frame — that is what gets tested.</p><p class="able"><b>Be able to</b> match each level to its managers, its scope and its time frame, and use the alternative corporate / business / functional framing.</p></div>'+
   '<p class="knowline"><span class="know">In seven of the ten sets</span></p>'+
   '<h3 class="sub" id="plan-levels3">The three levels</h3>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Level</th><th>Who</th><th>Scope</th><th>Time frame</th></tr></thead><tbody>'+
   '<tr><td class="head">Strategic</td><td class="sm"><b>Top management</b></td><td class="sm">The <b>whole organization</b> — its long-term goals and the mission. <b>Not</b> department-specific.</td><td class="sm"><b>1 to 5 years</b></td></tr>'+
   '<tr><td class="head">Tactical</td><td class="sm"><b>Middle management</b></td><td class="sm">The <b>departments</b> — the actions that carry out the strategic plan.</td><td class="sm"><b>6 to 24 months</b></td></tr>'+
   '<tr><td class="head">Operational</td><td class="sm"><b>First-line management</b></td><td class="sm"><b>Specific short-term tasks</b> in a work unit — the day-to-day.</td><td class="sm"><b>1 to 52 weeks</b></td></tr>'+
   '</tbody></table></div>'+
   '<div class="exam-tip"><b>The sets disagree on tactical</b>One set says 6&ndash;24 <i>weeks</i>; the textbook figure is 6&ndash;24 <b>months</b>, with operational plans at 1&ndash;52 weeks. If a question gives both, months is tactical and weeks is operational.</div>'+
   '<p><b>The other framing.</b> Two sets ask the same idea as <b>corporate / business / functional</b> levels: corporate strategy is the whole company (&ldquo;be number one or two in every industry we are in&rdquo; is corporate), business strategy is one division competing in its market, functional strategy is one department&rsquo;s contribution.</p>'+
   '<h3 class="sub" id="plan-time">Short-term and long-term</h3>'+
   '<ul><li><b>Short-term plans</b> cover a year or less; <b>long-term plans</b> go beyond three years (some sets say beyond one).</li><li>Strategic plans are long-term by nature; operational plans are short-term.</li><li>Goals can be <b>specific</b> (clear, measurable) or <b>directional</b> (general guidelines); plans can be <b>stated goals</b> (what the organization says) or <b>real goals</b> (what it actually pursues).</li></ul>'},

  {id:"plan-types", h:"Standing and Single-Use Plans", body:
   '<div class="point"><b>The point</b><p>Plans come in two families. <b>Standing plans</b> are used over and over for recurring situations — a <b>policy</b>, a <b>procedure</b>, a <b>rule</b>, in order from broadest to most specific. <b>Single-use plans</b> are for a situation that happens once — a <b>program</b>, a <b>project</b>, a <b>budget</b>.</p><p class="able"><b>Be able to</b> classify a plan as standing or single-use, and tell a policy from a procedure from a rule.</p></div>'+
   '<p class="knowline"><span class="know">In four of the ten sets</span></p>'+
   '<h3 class="sub" id="plan-standing">Standing plans — for repeated situations</h3>'+
   '<div class="levels">'+
   '<div class="lv"><b>Policy</b><span>A <b>broad, general guideline</b> for making decisions — &ldquo;we promote from within where possible.&rdquo; Leaves room for judgment.</span></div>'+
   '<div class="lv"><b>Procedure</b><span>The <b>sequence of steps</b> to follow in a particular situation — how to process a refund, in order.</span></div>'+
   '<div class="lv"><b>Rule</b><span>A <b>specific, required action</b> with <b>no flexibility</b> — &ldquo;no smoking in the warehouse.&rdquo;</span></div></div>'+
   '<h3 class="sub" id="plan-single">Single-use plans — for one occasion</h3>'+
   '<ul><li><b>Program</b> — a single-use plan covering a <b>broad</b> set of activities, such as launching a new product line.</li><li><b>Project</b> — a single-use plan of <b>narrower</b> scope, often part of a program, such as building one store.</li><li><b>Budget</b> — a single-use plan that allocates resources in numbers for a set period. One set includes it explicitly.</li></ul>'},

  {id:"plan-smart", h:"SMART Goals, MBO and Stretch Goals", body:
   '<div class="point"><b>The point</b><p>A goal is only useful if it is well built. <b>SMART</b> is the checklist. <b>Management by objectives</b> is the process where managers and employees <b>set goals together</b> and then use them to evaluate. And a <b>stretch goal</b> is one set deliberately beyond what seems reachable.</p><p class="able"><b>Be able to</b> expand SMART, describe the MBO cycle and its author, and define stretch goals and BHAGs.</p></div>'+
   '<h3 class="sub" id="plan-smartlist">SMART goals</h3>'+
   '<p class="knowline"><span class="know">In four sets — with three different expansions</span></p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th></th><th>Version A</th><th>Version E</th><th>Version H</th></tr></thead><tbody>'+
   '<tr><td class="head">S</td><td class="sm">Specific</td><td class="sm">Specific</td><td class="sm">Specific</td></tr>'+
   '<tr><td class="head">M</td><td class="sm">Measurable</td><td class="sm">Measurable</td><td class="sm">Measurable</td></tr>'+
   '<tr><td class="head">A</td><td class="sm"><b>Attainable</b></td><td class="sm"><b>Action-oriented</b></td><td class="sm"><b>Achievable</b></td></tr>'+
   '<tr><td class="head">R</td><td class="sm"><b>Results-oriented</b></td><td class="sm"><b>Realistic</b></td><td class="sm"><b>Relevant</b></td></tr>'+
   '<tr><td class="head">T</td><td class="sm"><b>Target dates</b></td><td class="sm"><b>Time-bound</b></td><td class="sm"><b>Time-based</b></td></tr>'+
   '</tbody></table></div>'+
   '<div class="exam-tip"><b>Which one to give</b>S and M are the same everywhere; only A, R and T vary. Use the expansion in <b>your textbook</b>. Version A — Specific, Measurable, Attainable, Results-oriented, Target dates — is the one in the set titled exactly like this course. Whatever the letters, the idea is the same: a goal you can measure, with a deadline, that is challenging but reachable and tied to results.</div>'+
   '<h3 class="sub" id="plan-mbo">Management by objectives</h3>'+
   '<p class="knowline"><span class="know">In five of the ten sets</span></p>'+
   '<p>MBO was developed by <b>Peter Drucker</b> in <b>1954</b>. It is a four-step cycle in which managers and employees set goals <b>jointly</b> and then use those goals to monitor and evaluate performance:</p>'+
   '<div class="flow"><div class="step"><b>1 · Jointly set objectives</b>Manager and employee agree the goals together — that is the defining feature.</div><div class="step"><b>2 · Develop action plans</b>How each objective will be reached.</div><div class="step"><b>3 · Review periodically</b>Progress is checked and plans adjusted.</div><div class="step"><b>4 · Appraise and reward</b>Performance is judged against the objectives, and rewarded.</div></div>'+
   '<p>The objectives can be <b>improvement</b> objectives, <b>personal development</b> objectives or <b>maintenance</b> objectives. The related idea of <b>management by means (MBM)</b> shifts the focus from the results to the <b>methods and processes</b> that produce them.</p>'+
   '<h3 class="sub" id="plan-stretch">Stretch goals, BHAGs and cascading</h3>'+
   '<ul><li>A <b>stretch goal</b> is ambitious — beyond what seems reachable — but still realistic enough to motivate rather than discourage.</li><li>A <b>BHAG</b> (big hairy audacious goal) is Collins and Porras&rsquo;s term for a bold long-term goal that galvanises the whole organization.</li><li><b>Cascading goals</b> flow from the top down so that each level&rsquo;s goals support the level above.</li></ul>'},

  {id:"plan-contingency", h:"Contingency, Scenario and Crisis Planning", body:
   '<div class="point"><b>The point</b><p>A plan assumes a future; these are the plans for when the future does not cooperate. A <b>contingency plan</b> is the alternative action for when things go wrong. <b>Scenario planning</b> writes plans for several possible futures. <b>Crisis planning</b> is prevention and preparation for the worst.</p><p class="able"><b>Be able to</b> define each one and say when it is used.</p></div>'+
   '<p class="knowline"><span class="know">In four of the ten sets</span></p>'+
   '<ul><li><b>Contingency planning</b> — an <b>alternative course of action</b> for a specific thing that could go wrong: the supplier fails, the launch slips. &ldquo;If X, then Y.&rdquo;</li>'+
   '<li><b>Scenario planning</b> (scenario analysis) — developing plans for <b>several plausible futures</b> at once, so the organization is ready for more than one.</li>'+
   '<li><b>Crisis planning</b> — two parts: <b>prevention</b> (spot the warning signs and head the crisis off) and <b>preparation</b> (a crisis team, a spokesperson, a plan, and rehearsal).</li>'+
   '<li>These belong with <b>forecasting</b>: a <b>trend analysis</b> projects the past into the future; contingency and scenario planning cover what a trend cannot foresee.</li></ul>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Planning","Setting goals and deciding how to achieve them — the most fundamental management function","g-plan-polc"],
   ["The four functions of management","Planning, organizing, leading, controlling","g-plan-polc"],
   ["Goal (objective)","A specific commitment to achieve a measurable result in a stated period — a future end","g-plan-polc"],
   ["Plan","The document outlining how a goal will be achieved — today’s means","g-plan-polc"],
   ["Planning/control cycle","Plan, carry out, control by comparing results with the plan, then correct","g-plan-polc"],
   ["Mission statement","Why the organization exists — its purpose, product or service, and what it does","g-plan-mission"],
   ["Vision statement","What the organization wants to become — its long-term direction","g-plan-mission"],
   ["Values statement","The core priorities and beliefs that guide how the organization behaves","g-plan-mission"],
   ["Strategic planning","Top management, the whole organization, one to five years","g-plan-levels"],
   ["Tactical planning","Middle management, the departments, six to twenty-four months — carrying out the strategy","g-plan-levels"],
   ["Operational planning","First-line management, specific short-term tasks, one to fifty-two weeks","g-plan-levels"],
   ["Standing plan","A plan used repeatedly for recurring situations — policy, procedure, rule","g-plan-types"],
   ["Policy","A broad, general guideline for decisions that leaves room for judgment","g-plan-types"],
   ["Procedure","The sequence of steps to follow in a particular situation","g-plan-types"],
   ["Rule","A specific required action with no flexibility","g-plan-types"],
   ["Single-use plan","A plan for a situation that will not recur — program, project, budget","g-plan-types"],
   ["Program","A single-use plan covering a broad set of activities","g-plan-types"],
   ["Project","A single-use plan of narrower scope, often part of a program","g-plan-types"],
   ["SMART goal","Specific, Measurable, Attainable, Results-oriented, with Target dates (the letters vary by book)","g-plan-smart"],
   ["Management by objectives (MBO)","Managers and employees jointly set goals, then use them to monitor and evaluate — Drucker, 1954","g-plan-smart"],
   ["Management by means (MBM)","Focusing on the methods and processes that produce results rather than the results alone","g-plan-smart"],
   ["Stretch goal","An ambitious goal beyond what seems reachable, but realistic enough to motivate","g-plan-smart"],
   ["BHAG","Collins and Porras’s big hairy audacious goal — bold and long term","g-plan-smart"],
   ["Cascading goals","Goals that flow down so each level supports the one above","g-plan-smart"],
   ["Contingency plan","An alternative course of action for a specific thing that could go wrong","g-plan-contingency"],
   ["Scenario planning","Developing plans for several plausible futures at once","g-plan-contingency"],
   ["Crisis planning","Prevention plus preparation for the worst — a team, a spokesperson, a rehearsed plan","g-plan-contingency"],
   ["Trend analysis","Projecting the past into the future as a forecast","g-plan-contingency"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["Which function is most fundamental","Planning — the other three carry out what was planned","g-plan-polc"],
   ["Goals vs plans","Goals are future ends (what); plans are today’s means (how)","g-plan-polc"],
   ["The foundation all other planning comes from","The mission — not the goals","g-plan-polc"],
   ["The three questions the statements answer","Mission: why do we exist? Vision: what do we want to become? Values: how will we behave?","g-plan-mission"],
   ["What a good mission statement does","Raises motivation and performance — people work harder for a purpose they understand","g-plan-mission"],
   ["The three levels and their managers","Strategic = top · tactical = middle · operational = first-line","g-plan-levels"],
   ["The three time frames","Strategic 1–5 years · tactical 6–24 months · operational 1–52 weeks","g-plan-levels"],
   ["The corporate / business / functional framing","Corporate = whole company · business = one division’s market · functional = one department","g-plan-levels"],
   ["Standing plans, broadest to most specific","Policy → procedure → rule","g-plan-types"],
   ["Single-use plans","Program (broad), project (narrower), budget","g-plan-types"],
   ["The four steps of MBO","Jointly set objectives → develop action plans → review periodically → appraise and reward","g-plan-smart"],
   ["Who developed MBO, and when","Peter Drucker, 1954","g-plan-smart"],
   ["The three types of MBO objective","Improvement, personal development, maintenance","g-plan-smart"],
   ["The three kinds of what-if planning","Contingency (one alternative), scenario (several futures), crisis (prevention and preparation)","g-plan-contingency"]]}
 ]
};

/* ---- planning questions ---- */
var QB = [
 {tp:"plan",sec:"g-plan-polc",t:"mc",q:"The four functions of management are:",a:"planning, organizing, leading and controlling",w:["planning, budgeting, staffing and reviewing","organizing, motivating, directing and reporting","forecasting, deciding, delegating and evaluating"],e:"POLC — and planning is the one the others follow from."},
 {tp:"plan",sec:"g-plan-polc",t:"mc",q:"Which management function is described as the most fundamental?",a:"Planning, because the other three carry out what was planned",w:["Controlling, because it catches every mistake the others make","Leading, because nothing happens without people to do it","Organizing, because resources have to exist before any plan"],e:"Organizing, leading and controlling all serve the plan."},
 {tp:"plan",sec:"g-plan-polc",t:"mc",q:"Planning is best defined as:",a:"setting goals and deciding how to achieve them",w:["arranging tasks and people so the work can be done","monitoring results and correcting them against a standard","motivating and directing people toward a shared purpose"],e:"The second option is organizing, the third controlling, the fourth leading."},
 {tp:"plan",sec:"g-plan-polc",t:"mc",q:"What is the difference between a goal and a plan?",a:"A goal is a future end to be achieved; a plan is the means of achieving it",w:["A goal is a broad statement of purpose; a plan is the mission that grows out of it", "A goal is set by first-line managers for a week; a plan is set by top managers for a year", "A goal is a rule that must be followed; a plan is a policy that leaves room for judgment"],e:"Goals say what; plans say how."},
 {tp:"plan",sec:"g-plan-polc",t:"mc",q:"All other planning in an organization is derived from its:",a:"mission",w:["budget","tactical plan","org chart"],e:"The mission is the foundation. One Quizlet answers this with “goals,” which is the wrong way round — goals come from the mission."},
 {tp:"plan",sec:"g-plan-polc",ap:true,t:"mc",q:"A manager compares this quarter’s sales with the target, finds a shortfall, and adjusts the sales plan. Which part of the planning/control cycle is that?",a:"Controlling the direction and correcting the plan",w:["Setting the original goal for the quarter","Organizing the sales team for the new quarter","Leading the team by explaining the shortfall"],e:"Plan, carry out, compare results with the plan, correct — this is the last step."},
 {tp:"plan",sec:"g-plan-polc",t:"tf",q:"Planning comes first because organizing, leading and controlling all exist to carry out the plan.",a:true,e:"True — that is exactly why the sets call it the most fundamental function."},
 {tp:"plan",sec:"g-plan-polc",t:"tf",q:"A plan describes the future result an organization wants; a goal describes how it will get there.",a:false,e:"False — it is the reverse. The goal is the end, the plan is the means."},

 {tp:"plan",sec:"g-plan-mission",t:"mc",q:"A mission statement expresses:",a:"the organization’s purpose or reason for existing",w:["the organization’s long-term picture of what it wants to become","the specific measurable targets for the coming year","the department-level actions that carry out the strategy"],e:"Why we exist. The second option is the vision."},
 {tp:"plan",sec:"g-plan-mission",t:"mc",q:"A vision statement expresses:",a:"what the organization wants to become — its long-term direction",w:["why the organization exists — its purpose, its product and the people it serves", "the specific, measurable targets each department must hit during the coming year", "how the organization will behave — the values it commits to along the way"],e:"What we want to become. The first option is the mission."},
 {tp:"plan",sec:"g-plan-mission",t:"mc",q:"A mission statement describes an organization’s basic product or service, its purpose, and what it does. Which of these does it include?",a:"All of the above",w:["Only its basic product or service","Only its purpose","Only what it does"],e:"When the sets list the three and offer “all of the above,” that is the answer."},
 {tp:"plan",sec:"g-plan-mission",t:"mc",q:"What effect does a well-designed mission statement have on employees?",a:"It raises motivation and performance, because people work harder for a purpose they understand",w:["It lowers motivation, because people feel their own goals matter less than the organization’s", "It has no measurable effect on employees, because it is written for investors and the public", "It reduces performance, because it adds a layer of approval and paperwork to every decision"],e:"Purpose motivates — which is why the sets ask about it."},
 {tp:"plan",sec:"g-plan-mission",ap:true,t:"mc",q:"A company’s statement reads: “To be the most trusted airline in the world by 2030.” Which kind of statement is it?",a:"A vision statement — it says what the company wants to become",w:["A mission statement — it says why the company exists and whom it serves", "A values statement — it says how the company will behave on the way there", "A tactical plan — it says what each department will do over the next two years"],e:"A future to become, with a horizon — vision."},
 {tp:"plan",sec:"g-plan-mission",ap:true,t:"mc",q:"A statement reads: “We exist to bring affordable, healthy meals to families who are short of time.” Which kind is it?",a:"A mission statement — it says why the company exists and whom it serves",w:["A vision statement — it says what the company wants to become by a certain date", "A rule — it specifies a required action that allows no flexibility at all", "An operational plan — it lists the specific tasks of one unit for the week"],e:"Purpose, product and customer — mission."},
 {tp:"plan",sec:"g-plan-mission",t:"tf",q:"The mission answers “why do we exist?” and the vision answers “what do we want to become?”",a:true,e:"True — the cleanest way to keep the two apart."},

 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"Strategic planning is done by which managers, for what scope?",a:"Top management, for the whole organization",w:["Middle management, for a single department","First-line management, for a single work unit","Every manager, each for their own team"],e:"The whole organization, over one to five years."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"Tactical planning is done by:",a:"middle managers, deciding how their departments will carry out the strategic plan",w:["top managers, setting the mission and the long-term goals for the whole organization", "first-line managers, scheduling the specific tasks of their units for the coming weeks", "the board of directors, approving the annual budget and the strategic direction"],e:"Middle management translating strategy into departmental action."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"Operational planning is done by:",a:"first-line managers, for specific short-term tasks in their units",w:["middle managers, for their departments over the next two years","top managers, for the whole organization over five years","outside consultants, for the organization’s long-term direction"],e:"The day-to-day, one to fifty-two weeks out."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"Which time frame goes with strategic planning?",a:"One to five years",w:["Six to twenty-four months","One to fifty-two weeks","One to seven days"],e:"Strategic 1–5 years, tactical 6–24 months, operational 1–52 weeks."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"Which time frame goes with tactical planning?",a:"Six to twenty-four months",w:["One to five years","One to fifty-two weeks","Ten years or more"],e:"One set says weeks; the textbook says months. Weeks is operational."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"GE’s goal to be “number one or number two in every industry we are in” is an example of strategy at which level?",a:"Corporate",w:["Business","Functional","Operational"],e:"It is about the whole company across all its industries — corporate. Business is one division; functional is one department."},
 {tp:"plan",sec:"g-plan-levels",t:"mc",q:"In the corporate / business / functional framing, business-level strategy is:",a:"how one division competes in its own market",w:["how the whole company decides which industries to be in","how one department such as marketing contributes","how first-line supervisors schedule daily work"],e:"Corporate is the whole company; business is one division; functional is one department."},
 {tp:"plan",sec:"g-plan-levels",ap:true,t:"mc",q:"The marketing department decides how it will support the company’s three-year growth strategy over the next eighteen months. Which level of planning is that?",a:"Tactical",w:["Strategic","Operational","Corporate"],e:"A department carrying out the strategy, over months — middle management’s job."},
 {tp:"plan",sec:"g-plan-levels",ap:true,t:"mc",q:"A shift supervisor works out the staffing rota for the next six weeks. Which level of planning is that?",a:"Operational",w:["Tactical","Strategic","Business"],e:"Specific, short-term, one work unit, first-line management."},
 {tp:"plan",sec:"g-plan-levels",t:"tf",q:"Strategic plans are specific to a single department.",a:false,e:"False — they cover the whole organization. Departmental plans are tactical. One set tests this exact statement as false."},
 {tp:"plan",sec:"g-plan-levels",t:"tf",q:"Short-term plans cover a year or less; long-term plans extend beyond three years.",a:true,e:"True — with strategic plans long term and operational plans short term."},

 {tp:"plan",sec:"g-plan-types",t:"mc",q:"A standing plan is:",a:"a plan used repeatedly for situations that recur — a policy, a procedure or a rule",w:["a plan for a situation that will not recur — a program, a project or a one-year budget", "a plan a manager keeps in reserve, to be used only if the main plan goes wrong", "a plan set by top management for the whole organization over one to five years"],e:"Standing = recurring. Single-use = once."},
 {tp:"plan",sec:"g-plan-types",t:"mc",q:"A policy is:",a:"a broad, general guideline for making decisions that leaves room for judgment",w:["a sequence of steps that must be followed, in order, in one particular situation", "a specific action that is required in every single case, with no flexibility whatever", "a single-use plan that covers a broad set of related activities over a year"],e:"Policy is the broadest standing plan; procedure and rule get more specific."},
 {tp:"plan",sec:"g-plan-types",t:"mc",q:"A procedure is:",a:"the sequence of steps to follow in a particular situation",w:["a broad guideline that leaves the decision to the manager","a required action that allows no exceptions whatever","a plan for a one-time event such as a product launch"],e:"Steps, in order."},
 {tp:"plan",sec:"g-plan-types",t:"mc",q:"A rule is:",a:"a specific required action that allows no flexibility",w:["a general guideline that a manager interprets case by case","a set of ordered steps for handling a recurring task","a single-use plan of narrow scope that is part of a program"],e:"No smoking in the warehouse — no judgment involved."},
 {tp:"plan",sec:"g-plan-types",t:"mc",q:"Which of these is a single-use plan?",a:"A project",w:["A policy","A procedure","A rule"],e:"Program, project and budget are single-use; policy, procedure and rule are standing."},
 {tp:"plan",sec:"g-plan-types",t:"mc",q:"What is the difference between a program and a project?",a:"A program is broader; a project is narrower and often part of a program",w:["A program is a standing plan; a project is a single-use plan for one occasion", "A program is set by first-line managers; a project is set by top managers alone", "A program is a broad guideline for decisions; a project is a required action"],e:"Both are single-use; the difference is scope."},
 {tp:"plan",sec:"g-plan-types",ap:true,t:"mc",q:"“All expense claims over $500 must be approved by a director.” Which kind of standing plan is that?",a:"A rule — a specific required action with no flexibility",w:["A policy — a broad guideline open to interpretation","A procedure — a sequence of steps to follow","A program — a broad single-use plan"],e:"Specific, required, no exceptions."},
 {tp:"plan",sec:"g-plan-types",ap:true,t:"mc",q:"“We prefer to promote from within whenever a suitable candidate exists.” Which kind of standing plan is that?",a:"A policy — a broad guideline that leaves room for judgment",w:["A rule — a required action with no exceptions","A procedure — the ordered steps for filling a vacancy","A project — a single-use plan of narrow scope"],e:"“Prefer” and “whenever suitable” are judgment words — policy."},
 {tp:"plan",sec:"g-plan-types",ap:true,t:"mc",q:"A company plans the opening of one new store next spring. Which kind of plan is that?",a:"A project — a single-use plan of narrow scope",w:["A policy — a standing guideline for decisions","A procedure — the steps for handling a recurring task","A rule — a required action with no flexibility"],e:"One occasion, narrow scope; the whole chain of openings would be a program."},
 {tp:"plan",sec:"g-plan-types",t:"tf",q:"A budget is a single-use plan.",a:true,e:"True — it allocates resources for one set period. One of the sets lists it alongside programs and projects."},

 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"In the SMART acronym, what do S and M stand for?",a:"Specific and Measurable — the same in every version",w:["Strategic and Managerial — the same in every version","Simple and Meaningful — the same in every version","Standing and Monitored — the same in every version"],e:"Only A, R and T vary between the sets."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"The goal “do better at customer service this year” fails the SMART test mainly because it is:",a:"not specific or measurable — there is no number and no clear target",w:["not time-bound — it names a year but gives no actual deadline within it", "not attainable — customer service cannot realistically be improved in a year", "not relevant — customer service is not something a business sets goals for"],e:"“Better” cannot be measured. Give it a number and a target."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"Management by objectives is:",a:"a process in which managers and employees jointly set goals and then use them to evaluate performance",w:["a process in which top managers set the goals and pass them down for employees to accept and carry out", "a process in which employees set their own goals without any involvement from their managers at all", "a process in which goals are replaced by detailed procedures and rules for every task an employee does"],e:"Jointly is the defining word."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"Who developed management by objectives, and when?",a:"Peter Drucker, in 1954",w:["Michael Porter, in 1980","Abraham Maslow, in 1943","Kurt Lewin, in 1947"],e:"Drucker, 1954 — three of the sets ask it."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"The four steps of MBO, in order, are:",a:"jointly set objectives → develop action plans → review periodically → appraise and reward",w:["appraise and reward → jointly set objectives → develop action plans → review periodically", "develop action plans → jointly set objectives → appraise and reward → review periodically", "review periodically → jointly set objectives → appraise and reward → develop action plans"],e:"Set, plan, review, reward."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"Management by means (MBM) is the approach that:",a:"focuses on the methods and processes that produce results rather than on the results alone",w:["sets the goals from the top down rather than jointly, and reviews them only at the year’s end", "abandons goals entirely in favour of detailed rules and procedures for every task in the unit", "measures only the financial results and ignores how the people and processes produced them"],e:"Means rather than ends."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"A stretch goal is:",a:"an ambitious goal beyond what seems reachable, but realistic enough to motivate",w:["a goal so easy that everyone is certain to reach it without any extra effort at all", "a goal with no deadline attached, so that it can be stretched over any period of time", "a goal that applies only to the physical fitness and the wellbeing of the employees"],e:"Challenging but not discouraging."},
 {tp:"plan",sec:"g-plan-smart",t:"mc",q:"A BHAG is:",a:"a big hairy audacious goal — Collins and Porras’s bold, long-term, galvanising goal",w:["a budget-holder’s annual goal, set by the finance department for each cost centre", "a behavioural goal used in employee performance reviews to track day-to-day conduct", "a backup goal that is used only when the main goal has clearly failed to be reached at all"],e:"Collins and Porras, Built to Last."},
 {tp:"plan",sec:"g-plan-smart",ap:true,t:"mc",q:"A manager and her employee sit down together, agree three targets for the quarter, write an action plan for each, meet monthly to check progress, and tie the year-end bonus to the results. What is that?",a:"Management by objectives",w:["Management by means","Scenario planning","A standing plan"],e:"All four MBO steps — jointly set, plan, review, reward."},
 {tp:"plan",sec:"g-plan-smart",ap:true,t:"mc",q:"“Increase repeat customers by 15% by December 31.” Which SMART elements does that goal clearly satisfy?",a:"Specific, measurable and time-bound, with a target date",w:["Only specific and relevant, since it names the customers", "Only time-bound and attainable, since it has a date", "None — it is a vision statement rather than a goal"],e:"A number (measurable), a clear subject (specific), a deadline (target date)."},
 {tp:"plan",sec:"g-plan-smart",t:"tf",q:"In MBO the manager sets the objectives alone and the employee is told what they are.",a:false,e:"False — they are set jointly. That is the whole point of the method."},
 {tp:"plan",sec:"g-plan-smart",t:"tf",q:"Cascading goals flow from the top of the organization down, so that each level’s goals support the level above.",a:true,e:"True."},

 {tp:"plan",sec:"g-plan-contingency",t:"mc",q:"A contingency plan is:",a:"an alternative course of action for a specific thing that could go wrong",w:["the main plan an organization follows when everything goes exactly as expected", "a plan for several different possible futures, all developed at the same time", "a plan that allocates resources in numbers for a set period, such as one year"],e:"If X happens, do Y."},
 {tp:"plan",sec:"g-plan-contingency",t:"mc",q:"Scenario planning is:",a:"developing plans for several plausible futures at once",w:["writing one detailed plan for the single most likely future","reviewing last year’s plan to see what went wrong","projecting a past trend forward to forecast next year"],e:"Ready for more than one future."},
 {tp:"plan",sec:"g-plan-contingency",t:"mc",q:"The two parts of crisis planning are:",a:"prevention and preparation",w:["forecasting and budgeting","recruitment and training","delegation and control"],e:"Head it off if you can; be ready if you cannot."},
 {tp:"plan",sec:"g-plan-contingency",t:"mc",q:"A trend analysis is:",a:"a forecast that projects the past into the future",w:["a plan for the single worst case the organization can imagine","a review of competitors’ strategies over the past year","a list of alternative actions for when a plan fails"],e:"Yesterday’s line, extended."},
 {tp:"plan",sec:"g-plan-contingency",ap:true,t:"mc",q:"An airline works out in advance what it will do if fuel prices double, if a pandemic grounds flights, and if a competitor starts a price war. What is it doing?",a:"Scenario planning",w:["Trend analysis","Management by objectives","Setting a standing plan"],e:"Several plausible futures, each with its own plan."},
 {tp:"plan",sec:"g-plan-contingency",ap:true,t:"mc",q:"A factory keeps a second supplier on standby in case its main supplier fails to deliver. What is that?",a:"A contingency plan",w:["A scenario plan","A stretch goal","A procedure"],e:"One specific thing that could go wrong, and the alternative for it."},
 {tp:"plan",sec:"g-plan-contingency",t:"tf",q:"Contingency planning and scenario planning cover what a trend analysis cannot foresee.",a:true,e:"True — a trend only extends the past; these prepare for breaks from it."}
];
