/* ================================================================ decisions
   Decision Making. Five sections, from the concept groups the ten sets share. */
CH.decide = {n:7, title:"Decision Making", short:"Decisions",
 notes:[
  {id:"dec-process", h:"The Rational Decision-Making Process", body:
   '<div class="point"><b>The point</b><p>A decision is a choice among alternatives. The <b>rational model</b> lays out how a manager <i>should</i> decide: <b>identify the problem first</b>, generate alternatives, evaluate and choose, implement, then evaluate the result. The sets count the steps differently — four, six, seven, eight — so <b>learn the order, not the number</b>.</p><p class="able"><b>Be able to</b> put the steps in order, say what the rational model assumes, and tell a problem from a symptom.</p></div>'+
   '<p class="knowline"><span class="know">In seven of the ten sets</span></p>'+
   '<h3 class="sub" id="dec-steps">The steps</h3>'+
   '<div class="flow"><div class="step"><b>1 · Identify the problem or opportunity</b>Always first. And identify the <b>problem</b>, not a <b>symptom</b> of it — falling sales is a symptom; the problem is what is causing them.</div><div class="step"><b>2 · Generate alternatives</b>The step that comes right after identifying the problem — the sets test that specifically. (The eight-step version puts &ldquo;identify criteria&rdquo; and &ldquo;weight criteria&rdquo; between them.)</div><div class="step"><b>3 · Evaluate the alternatives and select one</b>Against criteria: is it ethical, feasible, effective?</div><div class="step"><b>4 · Implement the decision</b>Put it into action.</div><div class="step"><b>5 · Evaluate the result</b>The final step — did it work? If not, adjust.</div></div>'+
   '<div class="exam-tip"><b>Two questions the sets ask outright</b>Which step comes right after identifying the problem? <b>Generating alternatives.</b> Which is the final step? <b>Evaluating the result.</b></div>'+
   '<h3 class="sub" id="dec-rational">The rational (classical) model</h3>'+
   '<ul><li>It describes how managers <b>should</b> make decisions — logically, to reach the <b>optimal</b> choice.</li><li>It <b>assumes</b> the manager has complete information, knows every alternative and its consequences, weighs them without bias, and picks the one that maximises value.</li><li>Those assumptions are rarely met in practice — which is what the next section is about.</li></ul>'},

  {id:"dec-nonrational", h:"Bounded Rationality, Satisficing and Intuition", body:
   '<div class="point"><b>The point</b><p>Real managers never have complete information or unlimited time. Their rationality is <b>bounded</b>, so they <b>satisfice</b> — take the first option that is <b>good enough</b> — or decide by <b>intuition</b>. The <b>administrative model</b> describes decisions as they actually happen, with both of those inside it.</p><p class="able"><b>Be able to</b> define bounded rationality, satisficing, intuition and evidence-based management, and recognise each in a story.</p></div>'+
   '<p class="knowline"><span class="know">In five of the ten sets</span></p>'+
   '<h3 class="sub" id="dec-satisficing">Bounded rationality and satisficing</h3>'+
   '<ul><li><b>Bounded rationality</b> (Herbert Simon): the ability to be rational is <b>limited by time, information and cognitive capacity</b>. Managers cannot see every alternative.</li><li><b>Satisficing</b>: choosing the <b>first alternative that is acceptable</b> — good enough — rather than searching for the optimal one. The car-shopping example in one set: you stop at the first car that meets your needs and price, not the best car on the market.</li><li>The <b>administrative model</b> of decision making includes both — it is how decisions are made under real constraints.</li></ul>'+
   '<div class="exam-tip"><b>A set gets this wrong</b>One Quizlet answers &ldquo;choosing the first acceptable alternative&rdquo; with <i>groupthink</i>. The answer is <b>satisficing</b>. Groupthink is about group pressure for unanimity — a different thing entirely.</div>'+
   '<h3 class="sub" id="dec-intuition">Intuition and evidence</h3>'+
   '<ul><li><b>Intuition</b>: deciding from <b>experience, gut feeling and accumulated judgment</b>, without conscious step-by-step reasoning. It is fast and often right for experts, but it is not the same as a programmed decision.</li><li><b>Evidence-based management</b>: translating principles based on the best available evidence into practice — deciding from facts rather than habit or hunch.</li></ul>'+
   '<div class="exam-tip"><b>The sets disagree here — go with intuition</b>One set calls a decision based on past experience &ldquo;programmed.&rdquo; Two others call it <b>intuition</b>, and that is the textbook answer. A <i>programmed</i> decision is a routine one handled by a rule; an <i>intuitive</i> one is a judgment call from experience.</div>'},

  {id:"dec-types", h:"Programmed vs Nonprogrammed, and How Much You Know", body:
   '<div class="point"><b>The point</b><p>Two ways to sort decisions. By <b>how routine</b> they are: programmed decisions recur and are handled by rules; nonprogrammed ones are unique and need a fresh solution. And by <b>how much the decision maker knows</b>: certainty, risk, uncertainty, ambiguity — a scale of less and less information.</p><p class="able"><b>Be able to</b> classify a decision as programmed or nonprogrammed and say who makes each, and place a situation on the certainty-to-ambiguity scale.</p></div>'+
   '<h3 class="sub" id="dec-programmed">Programmed versus nonprogrammed</h3>'+
   '<p class="knowline"><span class="know">In four of the ten sets</span></p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th></th><th>Programmed</th><th>Nonprogrammed</th></tr></thead><tbody>'+
   '<tr><td class="head">The problem</td><td class="sm"><b>Recurring, structured, routine</b></td><td class="sm"><b>Unique, unstructured</b>, often important</td></tr>'+
   '<tr><td class="head">The response</td><td class="sm">A ready-made <b>policy, procedure or rule</b></td><td class="sm">A <b>custom solution</b> worked out for this case</td></tr>'+
   '<tr><td class="head">Who decides</td><td class="sm"><b>Lower-level managers</b></td><td class="sm"><b>Higher-level managers</b></td></tr>'+
   '<tr><td class="head">Example</td><td class="sm">Reordering stock when it falls below a set level</td><td class="sm">Whether to enter a new country</td></tr>'+
   '</tbody></table></div>'+
   '<h3 class="sub" id="dec-conditions">Certainty, risk, uncertainty, ambiguity</h3>'+
   '<p class="knowline"><span class="know">In three of the ten sets</span></p>'+
   '<div class="levels">'+
   '<div class="lv"><b>Certainty</b><span>All the information needed is available; the outcome of each alternative is known.</span></div>'+
   '<div class="lv"><b>Risk</b><span>The alternatives and their probabilities are known, but not which outcome will occur.</span></div>'+
   '<div class="lv"><b>Uncertainty</b><span>The goals are clear but the information about alternatives and outcomes is incomplete — probabilities unknown.</span></div>'+
   '<div class="lv"><b>Ambiguity</b><span>The goals themselves are unclear, the alternatives are hard to define, and information is unavailable — the hardest condition.</span></div></div>'+
   '<p>The scale runs from most to least information. Most managerial decisions are made under <b>risk</b> or <b>uncertainty</b>.</p>'},

  {id:"dec-styles", h:"Decision Styles and Biases", body:
   '<div class="point"><b>The point</b><p>People decide differently. Two dimensions — <b>value orientation</b> (task versus people) and <b>tolerance for ambiguity</b> (low versus high) — give four <b>decision-making styles</b>. And everyone is subject to <b>biases</b>, the most tested being <b>escalation of commitment</b>: pouring more into a decision that is failing.</p><p class="able"><b>Be able to</b> name the four styles and the two dimensions behind them, and recognise escalation of commitment, the sunk-cost bias and the other common biases.</p></div>'+
   '<h3 class="sub" id="dec-styles4">The four styles</h3>'+
   '<p class="knowline"><span class="know">In four of the ten sets</span></p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Style</th><th>Tolerance for ambiguity</th><th>Value orientation</th><th>How they decide</th></tr></thead><tbody>'+
   '<tr><td class="head">Directive</td><td class="sm">Low</td><td class="sm">Task and technical</td><td class="sm">Efficient, logical, fast; little information, few alternatives; systematic.</td></tr>'+
   '<tr><td class="head">Analytical</td><td class="sm">High</td><td class="sm">Task and technical</td><td class="sm">Careful; wants more information and considers more alternatives; slow to decide.</td></tr>'+
   '<tr><td class="head">Conceptual</td><td class="sm">High</td><td class="sm">People and social</td><td class="sm">Broad, big-picture, creative; many alternatives; social and intuitive; long-range.</td></tr>'+
   '<tr><td class="head">Behavioral</td><td class="sm">Low</td><td class="sm">People and social</td><td class="sm">Works well with others, avoids conflict, receptive to suggestions.</td></tr>'+
   '</tbody></table></div>'+
   '<p>Other sets frame style as <b>linear versus nonlinear thinking</b> — a preference for external data and logic versus internal feelings and intuition. Same idea from a different book.</p>'+
   '<h3 class="sub" id="dec-biases">Biases and traps</h3>'+
   '<p class="knowline"><span class="know">Escalation of commitment is in three sets</span></p>'+
   '<ul><li><b>Escalation of commitment</b> — continuing to invest in a decision that is clearly failing, because so much has already been put in. The <b>sunk-cost</b> bias is its engine: money already spent should not affect the decision, but it does.</li><li><b>Availability</b> bias — judging by what comes easily to mind. <b>Representativeness</b> — generalising from a small or unrepresentative sample. <b>Confirmation</b> bias — seeking evidence that supports what you already believe. <b>Anchoring</b> — over-weighting the first number heard. <b>Overconfidence</b>. <b>Hindsight</b>. <b>Framing</b> — the same facts decided differently depending on how they are presented.</li><li><b>Heuristics</b> are the rules of thumb behind many of these — useful shortcuts that sometimes mislead.</li></ul>'},

  {id:"dec-group", h:"Group Decision Making and Groupthink", body:
   '<div class="point"><b>The point</b><p>Groups know more than any one member, but they also fail in predictable ways. The most tested failure is <b>groupthink</b>: <b>the desire for unanimity overrides realistic appraisal of the alternatives</b>. <b>Brainstorming</b> is the technique for getting ideas out without judging them.</p><p class="able"><b>Be able to</b> list the advantages and disadvantages of group decisions, define groupthink and say which groups are most prone to it, and describe brainstorming.</p></div>'+
   '<h3 class="sub" id="dec-prosons">Advantages and disadvantages</h3>'+
   '<div class="boxrow"><div class="box"><h4>Advantages</h4><ul><li>A <b>greater pool of knowledge</b></li><li><b>Different perspectives</b></li><li>Intellectual stimulation</li><li>Better understanding of the decision&rsquo;s reasoning</li><li>Deeper <b>commitment</b> to carrying it out</li></ul></div>'+
   '<div class="box"><h4>Disadvantages</h4><ul><li><b>A few people dominate</b> — one person&rsquo;s view carries the group</li><li><b>Groupthink</b></li><li><b>Satisficing</b> — the group settles for good enough to end the meeting</li><li><b>Goal displacement</b> — a secondary goal, like winning the argument, replaces the real one</li><li>It takes longer</li></ul></div></div>'+
   '<h3 class="sub" id="dec-groupthink">Groupthink</h3>'+
   '<p class="knowline"><span class="know">In six of the ten sets</span></p>'+
   '<ul><li>A cohesive group&rsquo;s members <b>strive for unanimity</b> and so <b>fail to realistically appraise</b> the alternatives. Agreement becomes more important than being right.</li><li><b>Cohesive groups are more prone</b> to it — the closer the group, the stronger the pressure not to dissent.</li><li>Symptoms: an illusion of invulnerability, self-censorship, pressure on dissenters, an illusion of unanimity.</li><li>Remedies: a devil&rsquo;s advocate, outside opinions, the leader withholding a view until others have spoken.</li></ul>'+
   '<h3 class="sub" id="dec-brainstorm">Brainstorming and the other techniques</h3>'+
   '<p class="knowline"><span class="know">In four of the ten sets</span></p>'+
   '<ul><li><b>Brainstorming</b>: a group generates as many ideas as possible while <b>withholding all criticism</b> — quantity first, judgment later. Electronic brainstorming, where ideas are typed anonymously, is also called <b>brainwriting</b>.</li><li><b>Delphi technique</b>: a series of questionnaires to experts who never meet, summarised between rounds.</li><li><b>Nominal group technique</b>: members write ideas silently, present them one by one, then vote.</li></ul>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Decision","A choice made from among available alternatives","g-dec-process"],
   ["Rational (classical) model","How managers should decide: logically, with full information, to reach the optimal choice","g-dec-process"],
   ["Problem vs symptom","Falling sales is a symptom; the problem is whatever is causing them — identify the problem, not the symptom","g-dec-process"],
   ["Bounded rationality","Rationality limited by time, information and cognitive capacity — Herbert Simon","g-dec-nonrational"],
   ["Satisficing","Choosing the first alternative that is good enough rather than searching for the optimal one","g-dec-nonrational"],
   ["Administrative model","Decision making as it really happens, under constraints — includes bounded rationality and satisficing","g-dec-nonrational"],
   ["Intuition","Deciding from experience, feeling and accumulated judgment without conscious reasoning","g-dec-nonrational"],
   ["Evidence-based management","Translating the best available evidence into management practice","g-dec-nonrational"],
   ["Programmed decision","A routine, recurring decision handled by a policy, procedure or rule — lower-level managers","g-dec-types"],
   ["Nonprogrammed decision","A unique, unstructured decision needing a custom solution — higher-level managers","g-dec-types"],
   ["Certainty","All needed information is available; outcomes are known","g-dec-types"],
   ["Risk","The alternatives and their probabilities are known, but not which outcome will occur","g-dec-types"],
   ["Uncertainty","Goals are clear but information on alternatives and outcomes is incomplete","g-dec-types"],
   ["Ambiguity","Goals unclear, alternatives hard to define, information unavailable — the hardest condition","g-dec-types"],
   ["Directive style","Low tolerance for ambiguity, task-oriented — fast, efficient, systematic","g-dec-styles"],
   ["Analytical style","High tolerance for ambiguity, task-oriented — wants more information and alternatives","g-dec-styles"],
   ["Conceptual style","High tolerance for ambiguity, people-oriented — big picture, creative, intuitive","g-dec-styles"],
   ["Behavioral style","Low tolerance for ambiguity, people-oriented — collaborative, avoids conflict","g-dec-styles"],
   ["Escalation of commitment","Continuing to invest in a decision that is clearly failing","g-dec-styles"],
   ["Sunk-cost bias","Letting money already spent, which cannot be recovered, affect a decision","g-dec-styles"],
   ["Heuristic","A rule of thumb — a useful shortcut that sometimes misleads","g-dec-styles"],
   ["Groupthink","A cohesive group’s desire for unanimity overrides its realistic appraisal of alternatives","g-dec-group"],
   ["Goal displacement","A secondary goal, like winning the argument, replaces the group’s real goal","g-dec-group"],
   ["Brainstorming","Generating as many ideas as possible while withholding criticism","g-dec-group"],
   ["Brainwriting","Electronic brainstorming — ideas typed, often anonymously","g-dec-group"],
   ["Delphi technique","Rounds of questionnaires to experts who never meet, summarised between rounds","g-dec-group"],
   ["Nominal group technique","Silent idea writing, one-by-one presentation, then a vote","g-dec-group"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["The decision steps, in order","Identify the problem → generate alternatives → evaluate and choose → implement → evaluate the result","g-dec-process"],
   ["The step after identifying the problem","Generating alternatives","g-dec-process"],
   ["The final step","Evaluating the result","g-dec-process"],
   ["What the rational model assumes","Complete information, every alternative known, no bias, the optimal choice","g-dec-process"],
   ["What bounds rationality","Time, information and cognitive capacity","g-dec-nonrational"],
   ["“First acceptable alternative” is","Satisficing — the good-enough choice","g-dec-nonrational"],
   ["A decision from past experience is","Intuitive — a judgment call from experience","g-dec-nonrational"],
   ["Programmed vs nonprogrammed: who decides","Programmed = lower-level managers · nonprogrammed = higher-level managers","g-dec-types"],
   ["The scale of decision conditions","Certainty → risk → uncertainty → ambiguity, with less information at each step","g-dec-types"],
   ["The two dimensions behind the four styles","Value orientation (task vs people) and tolerance for ambiguity (low vs high)","g-dec-styles"],
   ["The four decision styles","Directive, analytical, conceptual, behavioral","g-dec-styles"],
   ["The four disadvantages of group decisions","A few dominate · groupthink · satisficing · goal displacement","g-dec-group"],
   ["Which groups are most prone to groupthink","Cohesive ones — the closer the group, the stronger the pressure not to dissent","g-dec-group"],
   ["The rule of brainstorming","Withhold criticism — quantity first, judgment later","g-dec-group"]]}
 ]
};

/* ---- decision questions ---- */
QB = QB.concat([
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"What is the first step in the decision-making process?",a:"Identify the problem or opportunity",w:["Generate a list of alternatives","Evaluate the alternatives and select one","Implement the chosen alternative"],e:"Always first — and the problem, not a symptom."},
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"Which step comes immediately after identifying the problem?",a:"Generating alternatives",w:["Implementing the decision","Evaluating the result","Appraising and rewarding performance"],e:"Three of the sets ask this exact question."},
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"What is the final step of the decision-making process?",a:"Evaluating the result",w:["Selecting the best alternative","Identifying the decision criteria","Implementing the decision"],e:"Did it work? If not, adjust."},
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"The rational model of decision making describes:",a:"how managers should decide — logically, to reach the optimal choice",w:["how managers actually decide under real limits of time and information","how groups decide when the pressure for agreement is strongest","how routine decisions are handled by policies and rules"],e:"Should, not do. The administrative model describes what actually happens."},
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"The rational model assumes that the decision maker:",a:"has complete information, knows every alternative and picks the one that maximises value",w:["has limited information and limited time, and so picks the first alternative that is good enough", "relies on experience and gut feeling rather than on any step-by-step analysis", "follows whatever the majority of the group prefers, in order to keep the peace"],e:"Assumptions rarely met in practice — hence bounded rationality."},
 {tp:"decide",sec:"g-dec-process",t:"mc",q:"When the alternatives are evaluated in the rational model, the questions asked of each one are whether it is:",a:"ethical, feasible and effective",w:["cheap, popular and quick to explain","new, untested and different from rivals","proposed by the senior manager present"],e:"Is it right, can it be done, and will it solve the problem?"},
 {tp:"decide",sec:"g-dec-process",ap:true,t:"mc",q:"Sales have fallen for three months. A manager decides the problem is “falling sales” and starts generating ways to raise them. What has he done wrong?",a:"He has identified a symptom rather than the underlying problem",w:["He has skipped the step of implementing the decision before evaluating it", "He has evaluated the alternatives before he has finished generating them", "Nothing — falling sales is the problem, and generating ideas is the next step"],e:"Falling sales is what you can see; the problem is what is causing it."},
 {tp:"decide",sec:"g-dec-process",ap:true,t:"mc",q:"A manager has chosen a new supplier and signed the contract. What should happen next, according to the process?",a:"Implement the decision, then evaluate whether it worked",w:["Generate alternatives to the supplier she has chosen","Identify the problem the new supplier is meant to solve","Return to the step of weighting the decision criteria"],e:"Choosing is not the end; implementing and evaluating follow."},
 {tp:"decide",sec:"g-dec-process",t:"tf",q:"In the decision-making process, alternatives are generated before the problem is identified.",a:false,e:"False — the problem is always identified first."},

 {tp:"decide",sec:"g-dec-nonrational",t:"mc",q:"Choosing the first alternative that is acceptable rather than searching for the optimal one is called:",a:"satisficing",w:["groupthink","escalation of commitment","brainstorming"],e:"One set answers this with groupthink. It is satisficing."},
 {tp:"decide",sec:"g-dec-nonrational",t:"mc",q:"Bounded rationality means that:",a:"the ability to be rational is limited by time, information and cognitive capacity",w:["managers refuse to consider any alternative that comes from outside their own department", "decisions must be approved by a committee before they can take effect anywhere", "every decision is made with complete information, unlimited time and no bias at all"],e:"Herbert Simon — the limits that make satisficing necessary."},
 {tp:"decide",sec:"g-dec-nonrational",t:"mc",q:"Which model of decision making includes both bounded rationality and satisficing?",a:"The administrative model",w:["The rational (classical) model","The programmed model","The intuitive model"],e:"Decision making as it really happens under constraints."},
 {tp:"decide",sec:"g-dec-nonrational",t:"mc",q:"A decision made on the basis of past experience and gut feeling is best described as:",a:"intuitive",w:["programmed","rational","satisficing"],e:"Two sets say intuition; one says programmed. Intuition is the textbook answer — programmed decisions are routine ones handled by rules."},
 {tp:"decide",sec:"g-dec-nonrational",t:"mc",q:"Evidence-based management is:",a:"translating the best available evidence into management practice",w:["relying on the intuition of the most experienced manager present","following the rules and procedures written in the policy manual","choosing whichever option the majority of employees prefer"],e:"Facts over habit or hunch."},
 {tp:"decide",sec:"g-dec-nonrational",ap:true,t:"mc",q:"Shopping for a car, a buyer stops at the first one that meets his needs and budget instead of comparing every model on the market. What is that?",a:"Satisficing",w:["Escalation of commitment","Groupthink","Evidence-based management"],e:"Good enough, not optimal — the example one of the sets uses."},
 {tp:"decide",sec:"g-dec-nonrational",ap:true,t:"mc",q:"A chef with twenty years’ experience tastes a sauce and immediately knows what it needs, without working through any steps. That decision is:",a:"intuitive",w:["programmed","nonprogrammed","satisficing"],e:"Experience and judgment without conscious reasoning."},
 {tp:"decide",sec:"g-dec-nonrational",t:"tf",q:"Satisficing means selecting the optimal alternative after considering every option.",a:false,e:"False — that is the rational model. Satisficing takes the first good-enough option."},
 {tp:"decide",sec:"g-dec-nonrational",t:"tf",q:"Bounded rationality explains why managers satisfice rather than optimise.",a:true,e:"True — with limited time and information, good enough is what is possible."},

 {tp:"decide",sec:"g-dec-types",t:"mc",q:"A programmed decision is:",a:"a routine, recurring decision handled by a policy, procedure or rule",w:["a unique, unstructured decision that needs a custom solution worked out for the case", "a decision made by a computer program rather than by a manager or an employee", "a decision made on the basis of past experience, gut feeling and intuition"],e:"Recurring and structured — lower-level managers handle them."},
 {tp:"decide",sec:"g-dec-types",t:"mc",q:"A nonprogrammed decision is:",a:"a unique, unstructured, often important decision that needs a custom solution",w:["a routine, recurring decision handled by an existing policy, procedure or rule", "a decision that was not planned in advance and so is made at random, without analysis", "a decision that lower-level managers make every day as part of their normal work"],e:"Higher-level managers, one-off situations."},
 {tp:"decide",sec:"g-dec-types",t:"mc",q:"Which managers typically make programmed decisions, and which make nonprogrammed ones?",a:"Lower-level managers make programmed decisions; higher-level managers make nonprogrammed ones",w:["Higher-level managers make programmed decisions; lower-level managers make nonprogrammed ones","All managers make both kinds equally, regardless of level","Only top management makes decisions of either kind"],e:"Routine at the bottom, unique at the top."},
 {tp:"decide",sec:"g-dec-types",t:"mc",q:"A decision made under certainty is one where:",a:"all the information needed is available and the outcome of each alternative is known",w:["the alternatives and their probabilities are known, but not which outcome will occur", "the goals are clear but the information on the alternatives and outcomes is incomplete", "even the goals are unclear, the alternatives are hard to define and information is missing"],e:"The second is risk, the third uncertainty, the fourth ambiguity."},
 {tp:"decide",sec:"g-dec-types",t:"mc",q:"A decision made under risk is one where:",a:"the alternatives and their probabilities are known, but not which outcome will occur",w:["every outcome is known in advance, because all of the needed information is available", "the goals themselves are unclear and the information needed is simply unavailable", "no alternatives can be identified at all, and so the decision is postponed indefinitely"],e:"You can put odds on it — that is what separates risk from uncertainty."},
 {tp:"decide",sec:"g-dec-types",t:"mc",q:"The most difficult decision condition, where even the goals are unclear, is:",a:"ambiguity",w:["uncertainty","risk","certainty"],e:"Certainty → risk → uncertainty → ambiguity, with less information at each step."},
 {tp:"decide",sec:"g-dec-types",ap:true,t:"mc",q:"A store manager reorders stock every time it falls below fifty units, following the company’s reorder rule. That decision is:",a:"programmed",w:["nonprogrammed","made under ambiguity","intuitive"],e:"Recurring, structured, handled by a rule."},
 {tp:"decide",sec:"g-dec-types",ap:true,t:"mc",q:"A CEO must decide whether to open the company’s first factory in another continent. That decision is:",a:"nonprogrammed",w:["programmed","made under certainty","a standing plan"],e:"Unique, unstructured, important — a higher-level manager’s custom decision."},
 {tp:"decide",sec:"g-dec-types",ap:true,t:"mc",q:"A manager knows a new product has a 60% chance of succeeding and a 40% chance of failing. Under which condition is she deciding?",a:"Risk",w:["Certainty","Uncertainty","Ambiguity"],e:"Known alternatives with known probabilities."},
 {tp:"decide",sec:"g-dec-types",t:"tf",q:"Most managerial decisions are made under certainty.",a:false,e:"False — most are made under risk or uncertainty."},

 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"The four decision-making styles are:",a:"directive, analytical, conceptual and behavioral",w:["rational, bounded, intuitive and evidence-based","programmed, nonprogrammed, certain and uncertain","strategic, tactical, operational and functional"],e:"From two dimensions: value orientation and tolerance for ambiguity."},
 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"The two dimensions behind the four decision styles are:",a:"value orientation and tolerance for ambiguity",w:["speed of decision and cost of decision","level of management and size of the group","risk and certainty"],e:"Task versus people; low versus high tolerance for ambiguity."},
 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"The conceptual decision style is:",a:"big-picture, creative and intuitive, with a high tolerance for ambiguity and a people orientation",w:["fast, efficient and systematic, with a low tolerance for ambiguity and a strong task orientation", "careful and data-driven, wanting more information and more alternatives before deciding", "collaborative and conflict-avoiding, with a low tolerance for ambiguity and a people orientation"],e:"One set describes it as social, intuitive and big-picture."},
 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"The directive decision style is:",a:"efficient, logical and fast, using little information and few alternatives",w:["slow and careful, considering many alternatives and a great deal of data first", "creative and long-range, drawing on many people’s ideas and many alternatives", "receptive to others’ suggestions and focused above all on avoiding conflict"],e:"Low tolerance for ambiguity, task-oriented."},
 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"Escalation of commitment is:",a:"continuing to invest in a decision that is clearly failing",w:["committing more resources to a decision that is clearly succeeding","refusing to make any decision until all the information is in","persuading a group to agree by increasing the pressure for unanimity"],e:"Throwing good money after bad — the sunk-cost bias is its engine."},
 {tp:"decide",sec:"g-dec-styles",t:"mc",q:"The sunk-cost bias is:",a:"letting money already spent, which cannot be recovered, affect a decision about the future",w:["ignoring the costs of a project because they were paid for by another department’s budget", "choosing the cheapest alternative regardless of its quality or its fit with the goal", "assuming that a decision that cost a great deal of money must therefore have been a good one"],e:"Past spending is gone whatever you decide — but people count it anyway."},
 {tp:"decide",sec:"g-dec-styles",ap:true,t:"mc",q:"A project is two years late and far over budget, and every review says it will not work. The sponsor approves more funding “because we have already spent so much.” What is that?",a:"Escalation of commitment, driven by the sunk-cost bias",w:["Satisficing, driven by bounded rationality","Groupthink, driven by pressure for unanimity","A programmed decision, driven by a standing rule"],e:"The classic form of the trap."},
 {tp:"decide",sec:"g-dec-styles",ap:true,t:"mc",q:"A manager decides quickly, on limited information, preferring a clear rule to a long analysis. Which style is that?",a:"Directive",w:["Analytical","Conceptual","Behavioral"],e:"Low tolerance for ambiguity, task focus, speed."},
 {tp:"decide",sec:"g-dec-styles",ap:true,t:"mc",q:"After hearing that a competitor priced a product at $500, a manager cannot stop treating $500 as the right price even though her own costs suggest otherwise. Which bias is that?",a:"Anchoring",w:["Confirmation bias","Availability bias","Hindsight bias"],e:"Over-weighting the first number heard."},
 {tp:"decide",sec:"g-dec-styles",t:"tf",q:"Heuristics are rules of thumb that are always harmful and should never be used.",a:false,e:"False — they are useful shortcuts that sometimes mislead."},

 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Groupthink is:",a:"a cohesive group’s desire for unanimity overriding its realistic appraisal of alternatives",w:["a group’s tendency to accept the first alternative that is good enough, to end the meeting", "a technique for generating as many ideas as possible while withholding all criticism", "the domination of a group’s decision by its most senior or most talkative member"],e:"Agreement becomes more important than being right. Six of the sets test it."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Which groups are most prone to groupthink?",a:"Cohesive groups, where the pressure not to dissent is strongest",w:["Newly formed groups whose members do not know each other","Groups with a strong devil’s advocate and outside advisers","Groups that make only programmed decisions"],e:"Closeness breeds silence."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Which of these is an advantage of group decision making?",a:"A greater pool of knowledge and more perspectives",w:["It is always faster than an individual decision","One person’s view can carry the whole group","Members settle for a good-enough option to end the meeting"],e:"The other three are disadvantages — or, in the case of speed, simply false."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Which of these is a disadvantage of group decision making?",a:"One person may dominate the discussion",w:["A greater pool of knowledge","Deeper commitment to the decision","A better understanding of the reasoning"],e:"Domination, satisficing and goal displacement are three of the four; the pressure to agree is the fourth."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Goal displacement in a group means:",a:"a secondary goal, such as winning the argument, replaces the group’s real goal",w:["the group moves its deadline back to allow more discussion of the alternatives", "the leader replaces the group’s stated goal with a goal of her own choosing", "the group achieves a different goal from the one it set, entirely by accident"],e:"The meeting becomes about the meeting."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Brainstorming is:",a:"generating as many ideas as possible while withholding criticism",w:["evaluating each idea critically as soon as it is suggested","asking a panel of experts a series of questionnaires without meeting","having members write ideas silently and then vote on them"],e:"Quantity first, judgment later. The third option is the Delphi technique; the fourth is nominal group."},
 {tp:"decide",sec:"g-dec-group",t:"mc",q:"Electronic brainstorming, where ideas are typed rather than spoken, is also called:",a:"brainwriting",w:["the Delphi technique","the nominal group technique","groupthink"],e:"Anonymity takes away the pressure to agree with the room."},
 {tp:"decide",sec:"g-dec-group",ap:true,t:"mc",q:"A close-knit executive team approves a risky acquisition. Two members had doubts but said nothing, because everyone else seemed enthusiastic. What happened?",a:"Groupthink",w:["Satisficing","Brainstorming","Escalation of commitment"],e:"Self-censorship and an illusion of unanimity — in a cohesive group."},
 {tp:"decide",sec:"g-dec-group",ap:true,t:"mc",q:"A team leader tells the group: “Say every idea you have, no matter how odd — nobody comments until the list is done.” What technique is that?",a:"Brainstorming",w:["The Delphi technique","The nominal group technique","Management by objectives"],e:"Withhold criticism, generate freely."},
 {tp:"decide",sec:"g-dec-group",t:"tf",q:"A good remedy for groupthink is to have the leader state a preferred option at the start of the meeting.",a:false,e:"False — that increases the pressure to agree. Leaders should withhold their view until others have spoken."},
 {tp:"decide",sec:"g-dec-group",t:"tf",q:"Satisficing can happen in groups as well as individuals — a group may settle for a good-enough option to end the discussion.",a:true,e:"True — it is one of the four listed disadvantages of group decisions."}
]);
