/* ================================================================ people
   People & Change: the chapters only a few of the ten sets reach. Lighter
   weight, but on the page in case the exam goes there.                       */
CH.people = {n:9, title:"People & Change", short:"People",
 notes:[
  {id:"ppl-change", h:"Managing Change", body:
   '<div class="point"><b>The point</b><p>Change follows Kurt Lewin&rsquo;s three stages: <b>unfreeze</b> (create the motivation to change &mdash; show why the old way must go), <b>change</b> (learn the new behaviors), <b>refreeze</b> (reinforce the new behaviors so they stick). People resist change for predictable reasons, and there are known ways to reduce the resistance.</p><p class="able"><b>Be able to</b> give Lewin&rsquo;s stages in order and recognise each in a story, list why people resist change and how to overcome it, and define a learning organization.</p></div>'+
   '<p class="knowline"><span class="know">In three of the ten sets</span></p>'+
   '<h3 class="sub" id="ppl-lewin">Lewin&rsquo;s change model</h3>'+
   '<div class="flow"><div class="step"><b>1 &middot; Unfreezing</b>Create the <b>motivation to change</b>: make people see that the current way is not working &mdash; the first stage.</div><div class="step"><b>2 &middot; Changing</b>The transition: people <b>learn the new behaviors</b>, with training, models and support.</div><div class="step"><b>3 &middot; Refreezing</b><b>Reinforce</b> and support the new ways &mdash; rewards, new procedures, new job descriptions &mdash; so people do not drift back.</div></div>'+
   '<ul><li><b>Forces for change</b> come from outside (demographics, the market, technology, social and political pressures) and from inside (employee problems, managers&rsquo; behavior). Change is <b>reactive</b> when it responds to a problem that has appeared, <b>proactive</b> when it is made in anticipation.</li>'+
   '<li><b>Why people resist</b>: fear of the unknown, self-interest, habit, loss of power or status, peer pressure, mistrust of management, a poor climate for change.</li>'+
   '<li><b>Overcoming resistance</b> (Kotter and Schlesinger): education and communication; <b>participation and involvement</b>; facilitation and support; negotiation and agreement; manipulation and co-optation; explicit and implicit coercion. Involvement works because people support what they help build.</li>'+
   '<li>A <b>learning organization</b> (Senge) actively creates, acquires and transfers knowledge and changes its behavior in response. <b>Innovation</b> can be product or process, incremental or radical. <b>Organizational development</b> (OD) is the planned, systematic use of behavioral science to improve an organization.</li></ul>'},

  {id:"ppl-motivation", h:"Motivation", body:
   '<div class="point"><b>The point</b><p>Motivation is the set of psychological processes that <b>arouse, direct and sustain</b> goal-directed behavior. <b>Content</b> theories say what people need (Maslow, Herzberg, McClelland); <b>process</b> theories say how motivation happens (expectancy, equity, goal-setting). Job design puts the theories to work.</p><p class="able"><b>Be able to</b> list Maslow&rsquo;s levels in order, tell hygiene factors from motivators, define the three parts of expectancy theory, and tell job enrichment from job enlargement.</p></div>'+
   '<p class="knowline"><span class="know">In two of the ten sets</span></p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Theory</th><th>The idea</th><th>The parts</th></tr></thead><tbody>'+
   '<tr><td class="head">Maslow&rsquo;s hierarchy</td><td class="sm">Five needs in order; a <b>lower need must be met</b> before the next one motivates.</td><td class="sm"><b>Physiological &rarr; safety &rarr; love (belonging) &rarr; esteem &rarr; self-actualization</b>.</td></tr>'+
   '<tr><td class="head">Herzberg&rsquo;s two-factor</td><td class="sm">Two separate scales.</td><td class="sm"><b>Hygiene factors</b> (pay, conditions, policies, supervision) prevent <i>dissatisfaction</i> but do not motivate. <b>Motivating factors</b> (achievement, recognition, responsibility, the work itself, advancement) create <i>satisfaction</i>.</td></tr>'+
   '<tr><td class="head">McClelland&rsquo;s acquired needs</td><td class="sm">Needs are learned.</td><td class="sm"><b>Achievement, affiliation, power</b>. (Alderfer&rsquo;s ERG: existence, relatedness, growth.)</td></tr>'+
   '<tr><td class="head">Expectancy (Vroom)</td><td class="sm">Effort depends on three beliefs multiplied together &mdash; any zero kills it.</td><td class="sm"><b>Expectancy</b>: effort &rarr; performance. <b>Instrumentality</b>: performance &rarr; reward. <b>Valence</b>: the value of the reward.</td></tr>'+
   '<tr><td class="head">Goal-setting (Locke &amp; Latham)</td><td class="sm"><b>Specific, challenging</b> goals with feedback motivate more than &ldquo;do your best.&rdquo;</td><td class="sm">Specific, difficult, accepted, with feedback.</td></tr>'+
   '<tr><td class="head">Equity (Adams)</td><td class="sm">People compare their <b>outcomes/inputs</b> ratio with others&rsquo;.</td><td class="sm">Perceived unfairness &rarr; reduce effort, seek more reward, or leave.</td></tr>'+
   '<tr><td class="head">Reinforcement (Skinner)</td><td class="sm">Behavior follows its consequences.</td><td class="sm">Positive reinforcement, negative reinforcement, extinction, punishment.</td></tr>'+
   '</tbody></table></div>'+
   '<ul><li><b>Extrinsic</b> rewards come from others (pay, praise); <b>intrinsic</b> rewards come from the work itself (interest, accomplishment).</li>'+
   '<li><b>Job design</b>: the job characteristics model names five core dimensions &mdash; skill variety, task identity, task significance, <b>autonomy</b>, feedback. <b>Job enrichment</b> adds <b>autonomy and responsibility</b> (vertical loading). <b>Job enlargement</b> adds more tasks at the same level (horizontal loading). <b>Job rotation</b> moves people between jobs.</li></ul>'},

  {id:"ppl-hr", h:"Human Resources", body:
   '<div class="point"><b>The point</b><p>Human resource management is planning for, attracting, developing and retaining an effective workforce. The pipeline: <b>job analysis</b> &rarr; a <b>job description</b> (what the job does) and a <b>job specification</b> (what the person needs) &rarr; recruiting &rarr; selection &rarr; training &rarr; appraisal &rarr; compensation. Over it all sits the law: <b>equal employment opportunity</b>, above all <b>Title VII</b>.</p><p class="able"><b>Be able to</b> tell a job description from a job specification, name what Title VII forbids, and tell a behavioral interview from a situational one.</p></div>'+
   '<p class="knowline"><span class="know">In three of the ten sets</span></p>'+
   '<ul><li><b>Job analysis</b> determines the basic elements of a job. It produces the <b>job description</b> &mdash; the tasks, duties and responsibilities &mdash; and the <b>job specification</b> &mdash; the minimum qualifications a person needs.</li>'+
   '<li><b>Recruiting</b> is internal (current employees) or external; a <b>realistic job preview</b> gives candidates the bad news with the good.</li>'+
   '<li><b>Selection</b>: application forms, interviews, tests (ability, performance, personality), background and reference checks. Interviews are <b>unstructured</b> (no fixed questions) or <b>structured</b> (the same questions for everyone): a <b>situational</b> interview asks what you <i>would</i> do; a <b>behavioral-description</b> interview asks what you <i>did</i> &mdash; past behavior predicts future behavior.</li>'+
   '<li><b>Training</b> teaches skills for the current job; <b>development</b> prepares people for future roles. <b>Performance appraisal</b> can be objective or subjective, formal or informal; a <b>360-degree</b> appraisal gathers ratings from the manager, peers, subordinates and sometimes customers.</li>'+
   '<li><b>Compensation</b> is wages or salary, incentives and benefits. Discipline, termination and unions (the National Labor Relations Board) close the cycle.</li></ul>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Law</th><th>What it does</th></tr></thead><tbody>'+
   '<tr><td class="head">Title VII, Civil Rights Act (1964)</td><td class="sm">Forbids employment discrimination on the basis of <b>race, color, religion, sex or national origin</b>. Enforced by the <b>EEOC</b>.</td></tr>'+
   '<tr><td class="head">Equal Pay Act (1963)</td><td class="sm">Equal pay for equal work regardless of sex.</td></tr>'+
   '<tr><td class="head">Age Discrimination in Employment Act (1967)</td><td class="sm">Protects workers aged <b>40 and over</b>.</td></tr>'+
   '<tr><td class="head">Americans with Disabilities Act (1990)</td><td class="sm">Forbids discrimination against qualified people with disabilities; requires reasonable accommodation.</td></tr>'+
   '</tbody></table></div>'+
   '<ul><li><b>Adverse impact</b>: a practice that seems neutral but disproportionately affects a protected group. <b>Affirmative action</b> actively seeks out members of under-represented groups.</li><li><b>Sexual harassment</b>: <b>quid pro quo</b> (job benefits for favors) or a <b>hostile work environment</b> (an offensive atmosphere).</li></ul>'},

  {id:"ppl-groups", h:"Groups, Communication and Leadership", body:
   '<div class="point"><b>The point</b><p>Three chapters in one section. <b>Groups</b> become teams, develop through stages and run on <b>norms</b>. <b>Communication</b> is a process with noise in it, and some media carry more than others. <b>Leadership</b> is influence, drawing on five sources of <b>power</b> and taking several styles.</p><p class="able"><b>Be able to</b> tell a group from a team and give Tuckman&rsquo;s stages in order, define norms; rank media by richness and define the grapevine; name the five sources of power and the main leadership styles.</p></div>'+
   '<p class="knowline"><span class="know">In three of the ten sets</span></p>'+
   '<h3 class="sub" id="ppl-groupsdev">Groups and teams</h3>'+
   '<ul><li>A <b>group</b> is two or more freely interacting people with shared norms and goals and a common identity. A <b>team</b> is a small group with <b>complementary skills</b>, committed to a <b>common purpose</b> and <b>mutually accountable</b>. Groups are formal (created by the organization) or informal (formed by the members).</li>'+
   '<li><b>Tuckman&rsquo;s stages</b>: <b>forming</b> (getting oriented) &rarr; <b>storming</b> (conflict over roles and leadership) &rarr; <b>norming</b> (standards and cohesion settle) &rarr; <b>performing</b> (the work gets done) &rarr; <b>adjourning</b> (the group disbands).</li>'+
   '<li><b>Norms</b> are the general guidelines or rules of behavior that most members follow &mdash; unwritten, but enforced. <b>Roles</b> are task roles (get the job done) and maintenance roles (keep the group together). <b>Cohesiveness</b> is the &ldquo;we&rdquo; feeling. <b>Social loafing</b> is putting in less effort in a group than alone.</li>'+
   '<li>Team types: cross-functional, self-managed, virtual. Conflict can be <b>functional</b> (constructive, about the task) or <b>dysfunctional</b> (personal).</li></ul>'+
   '<h3 class="sub" id="ppl-comm">Communication</h3>'+
   '<ul><li>The process: a <b>sender</b> encodes a <b>message</b>, sends it through a <b>medium</b>, the <b>receiver</b> decodes it and gives <b>feedback</b> &mdash; with <b>noise</b> interfering at every step.</li>'+
   '<li><b>Media richness</b>: how much information a medium carries. <b>Face-to-face</b> is the richest; then video and telephone; then email and personal written messages; <b>impersonal written reports, flyers and bulletins</b> are the leanest. Rich media for non-routine, ambiguous messages; lean media for routine ones.</li>'+
   '<li><b>Formal channels</b>: <b>vertical</b> (<b>downward</b> from managers to employees, <b>upward</b> from employees to managers), <b>horizontal</b> (between peers), external. <b>Informal channels</b>: the <b>grapevine</b> &mdash; the unofficial network, fast and about <b>75% accurate</b> &mdash; and management by wandering around.</li>'+
   '<li>Barriers: physical, semantic (words), personal. Nonverbal communication: eye contact, expression, posture, space, time.</li></ul>'+
   '<h3 class="sub" id="ppl-lead">Leadership and power</h3>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Source of power</th><th>Comes from</th><th>Kind</th></tr></thead><tbody>'+
   '<tr><td class="head">Legitimate</td><td class="sm">The formal position in the hierarchy.</td><td class="sm">Position power</td></tr>'+
   '<tr><td class="head">Reward</td><td class="sm">The ability to give rewards.</td><td class="sm">Position power</td></tr>'+
   '<tr><td class="head">Coercive</td><td class="sm">The ability to punish.</td><td class="sm">Position power</td></tr>'+
   '<tr><td class="head">Expert</td><td class="sm">Specialized knowledge or skill.</td><td class="sm">Personal power</td></tr>'+
   '<tr><td class="head">Referent</td><td class="sm">Being admired and identified with &mdash; charm, respect.</td><td class="sm">Personal power</td></tr>'+
   '</tbody></table></div>'+
   '<ul><li><b>Leadership</b> is the ability to influence people toward goals. Managing copes with complexity; leading copes with change.</li>'+
   '<li><b>Behavioral approaches</b>: <b>task-oriented</b> behavior (<b>initiating structure</b>) and <b>relationship-oriented</b> behavior (<b>consideration</b>), from the Ohio State and Michigan studies. Classic styles: <b>autocratic</b> (the leader decides), <b>democratic</b> or participative (the group takes part), <b>laissez-faire</b> (hands off).</li>'+
   '<li><b>Contingency approaches</b>: <b>Fiedler</b> &mdash; a leader&rsquo;s style is fixed, so match the leader to the situation; <b>House&rsquo;s path-goal</b> &mdash; the leader clears the path (directive, supportive, participative, achievement-oriented); <b>Hersey and Blanchard</b> &mdash; adjust to the followers&rsquo; readiness.</li>'+
   '<li><b>Transactional</b> leaders exchange rewards for performance and correct deviations; <b>transformational</b> leaders inspire followers to go beyond self-interest through vision and charisma (inspirational motivation, idealized influence, individualized consideration, intellectual stimulation). <b>Servant</b> leaders put followers first; <b>leader&ndash;member exchange</b> describes in-groups and out-groups.</li></ul>'},

  {id:"ppl-global", h:"Global Business and Culture", body:
   '<div class="point"><b>The point</b><p>Doing business across borders means trade barriers, a choice of how to enter a foreign market, and culture. The <b>ways in</b> run from cheapest and safest (exporting) to most costly and riskiest (a <b>wholly owned subsidiary</b>). Culture is read through <b>Hofstede&rsquo;s dimensions</b> and through how people treat <b>time</b> and <b>context</b>.</p><p class="able"><b>Be able to</b> tell a tariff from a quota, put the entry modes in order of risk and define licensing, name Hofstede&rsquo;s dimensions, and tell monochronic from polychronic and high-context from low-context.</p></div>'+
   '<p class="knowline"><span class="know">In two of the ten sets</span></p>'+
   '<h3 class="sub" id="ppl-entry">Trade barriers and ways to enter a foreign market</h3>'+
   '<ul><li><b>Tariff</b>: a <b>tax</b> on imported goods. <b>Import quota</b>: a <b>limit on the quantity</b> that may be imported. <b>Embargo</b>: a ban on trade with a country. <b>Sanctions</b>: trade penalties for political ends. Against them: free trade, the WTO, the World Bank and IMF, and trading blocs (USMCA, the EU, ASEAN, APEC).</li></ul>'+
   '<div class="levels">'+
   '<div class="lv"><b>Global outsourcing</b><span>Buying goods or services from suppliers abroad. Least risk.</span></div>'+
   '<div class="lv"><b>Exporting / importing</b><span>Selling abroad, or buying from abroad, often through agents. Cheap and low-risk.</span></div>'+
   '<div class="lv"><b>Licensing</b><span>A company <b>allows a foreign firm to make or sell its product</b> in return for a fee or royalty.</span></div>'+
   '<div class="lv"><b>Franchising</b><span>A form of licensing: the franchisee gets the <b>whole business system</b> &mdash; trademark, products, procedures &mdash; for fees. McDonald&rsquo;s abroad.</span></div>'+
   '<div class="lv"><b>Joint venture</b><span>A business formed <b>with a foreign partner</b> who shares ownership, risk and profit &mdash; a strategic alliance.</span></div>'+
   '<div class="lv"><b>Wholly owned subsidiary</b><span>A foreign operation <b>totally owned and controlled</b> by the parent. <b>Most costly, most risk, most control.</b></span></div></div>'+
   '<div class="exam-tip"><b>A set gets this wrong</b>One Quizlet answers &ldquo;buying the rights to make or sell a product abroad&rdquo; with <i>transnational strategy</i>. That is <b>licensing</b>.</div>'+
   '<p>Managers&rsquo; outlooks: <b>ethnocentric</b> (home country knows best), <b>polycentric</b> (let the locals run it), <b>geocentric</b> (take the best from everywhere).</p>'+
   '<h3 class="sub" id="ppl-hofstede">Culture</h3>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Hofstede dimension</th><th>The question it asks</th></tr></thead><tbody>'+
   '<tr><td class="head">Individualism vs collectivism</td><td class="sm">Do people look after themselves and value personal achievement, or put the group first? The <b>United States</b> is highly <b>individualistic</b>.</td></tr>'+
   '<tr><td class="head">Power distance</td><td class="sm">How much unequal distribution of power is accepted.</td></tr>'+
   '<tr><td class="head">Uncertainty avoidance</td><td class="sm">How much people prefer clear rules and structured situations over ambiguity.</td></tr>'+
   '<tr><td class="head">Masculinity vs femininity</td><td class="sm">Assertiveness and achievement versus caring and quality of life.</td></tr>'+
   '<tr><td class="head">Long-term vs short-term orientation</td><td class="sm">Thrift and persistence versus tradition and the present. (A sixth, indulgence vs restraint, was added later.)</td></tr>'+
   '</tbody></table></div>'+
   '<ul><li>The <b>GLOBE</b> project extended Hofstede to nine dimensions.</li>'+
   '<li><b>Low-context</b> cultures (the United States, Germany, Scandinavia) put the meaning in the <b>words</b>; <b>high-context</b> cultures (Japan, China, the Arab countries) read it from the <b>situation and the relationship</b>.</li>'+
   '<li><b>Monochronic</b> time (the United States, northern Europe): <b>one thing at a time</b>, punctuality, schedules, single-agenda meetings. <b>Polychronic</b> time (Latin America, the Middle East): <b>many things at once</b>, flexible, relationships before schedules.</li></ul>'+
   '<div class="exam-tip"><b>A set gets this wrong</b>One Quizlet answers a question about scheduled, one-agenda meetings in the United States with <i>polychronic</i>. The United States is <b>monochronic</b>.</div>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Unfreezing","Lewin’s first stage — creating the motivation to change","g-ppl-change"],
   ["Changing","Lewin’s second stage — learning the new behaviors","g-ppl-change"],
   ["Refreezing","Lewin’s third stage — reinforcing the new behaviors so they stick","g-ppl-change"],
   ["Reactive change","Change made in response to a problem that has already appeared","g-ppl-change"],
   ["Proactive change","Change made in anticipation, before problems arise","g-ppl-change"],
   ["Learning organization","One that actively creates, acquires and transfers knowledge and changes its behavior in response","g-ppl-change"],
   ["Motivation","The psychological processes that arouse, direct and sustain goal-directed behavior","g-ppl-motivation"],
   ["Maslow’s hierarchy","Physiological, safety, love (belonging), esteem, self-actualization — lower needs first","g-ppl-motivation"],
   ["Hygiene factors","Herzberg: pay, conditions, policies — prevent dissatisfaction but do not motivate","g-ppl-motivation"],
   ["Motivating factors","Herzberg: achievement, recognition, responsibility, the work itself — create satisfaction","g-ppl-motivation"],
   ["Expectancy","The belief that effort will lead to performance","g-ppl-motivation"],
   ["Instrumentality","The belief that performance will lead to the reward","g-ppl-motivation"],
   ["Valence","The value a person places on the reward","g-ppl-motivation"],
   ["Goal-setting theory","Specific, challenging goals with feedback motivate more than “do your best”","g-ppl-motivation"],
   ["Equity theory","People compare their outcomes-to-inputs ratio with others’ and react to unfairness","g-ppl-motivation"],
   ["Job enrichment","Adding autonomy and responsibility to a job — vertical loading","g-ppl-motivation"],
   ["Job enlargement","Adding more tasks at the same level — horizontal loading","g-ppl-motivation"],
   ["Job analysis","Determining the basic elements of a job","g-ppl-hr"],
   ["Job description","The tasks, duties and responsibilities of a job","g-ppl-hr"],
   ["Job specification","The minimum qualifications a person needs to perform a job","g-ppl-hr"],
   ["Title VII","Civil Rights Act of 1964: no employment discrimination by race, color, religion, sex or national origin","g-ppl-hr"],
   ["EEOC","The Equal Employment Opportunity Commission — enforces Title VII","g-ppl-hr"],
   ["Behavioral-description interview","Asks how the candidate actually handled a situation in the past","g-ppl-hr"],
   ["Situational interview","Asks what the candidate would do in a hypothetical situation","g-ppl-hr"],
   ["Adverse impact","A neutral-seeming practice that disproportionately affects a protected group","g-ppl-hr"],
   ["360-degree appraisal","Ratings from the manager, peers, subordinates and sometimes customers","g-ppl-hr"],
   ["Team","A small group with complementary skills, a common purpose and mutual accountability","g-ppl-groups"],
   ["Norms","The general guidelines or rules of behavior most group members follow","g-ppl-groups"],
   ["Storming","Tuckman’s conflict stage — over roles and leadership","g-ppl-groups"],
   ["Social loafing","Putting in less effort in a group than when working alone","g-ppl-groups"],
   ["Media richness","How much information a medium carries — face-to-face richest, written reports leanest","g-ppl-groups"],
   ["Grapevine","The informal, unofficial communication network — fast, about 75% accurate","g-ppl-groups"],
   ["Legitimate power","Power from the formal position in the hierarchy","g-ppl-groups"],
   ["Referent power","Power from being admired and identified with","g-ppl-groups"],
   ["Expert power","Power from specialized knowledge or skill","g-ppl-groups"],
   ["Transactional leadership","Exchanging rewards for performance and correcting deviations","g-ppl-groups"],
   ["Transformational leadership","Inspiring followers beyond self-interest through vision and charisma","g-ppl-groups"],
   ["Tariff","A tax on imported goods","g-ppl-global"],
   ["Import quota","A limit on the quantity of a product that may be imported","g-ppl-global"],
   ["Licensing","Allowing a foreign firm to make or sell your product for a fee","g-ppl-global"],
   ["Franchising","Licensing a whole business system — trademark, products, procedures","g-ppl-global"],
   ["Joint venture","A business formed with a foreign partner who shares ownership, risk and profit","g-ppl-global"],
   ["Wholly owned subsidiary","A foreign operation totally owned by the parent — most costly, most risk, most control","g-ppl-global"],
   ["Power distance","How much unequal distribution of power a culture accepts","g-ppl-global"],
   ["Uncertainty avoidance","How much a culture prefers clear rules and structure over ambiguity","g-ppl-global"],
   ["Monochronic time","One thing at a time, punctuality, schedules — the United States","g-ppl-global"],
   ["Polychronic time","Many things at once, flexible, relationships first — Latin America, the Middle East","g-ppl-global"],
   ["High-context culture","Meaning read from the situation and the relationship, not just the words","g-ppl-global"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["Lewin’s three stages, in order","Unfreezing → changing → refreezing","g-ppl-change"],
   ["The first stage of change","Unfreezing — create the motivation","g-ppl-change"],
   ["Ways to overcome resistance","Education and communication · participation · facilitation · negotiation · manipulation and co-optation · coercion","g-ppl-change"],
   ["Maslow’s five needs, lowest to highest","Physiological, safety, love, esteem, self-actualization","g-ppl-motivation"],
   ["The three parts of expectancy theory","Expectancy (effort → performance) · instrumentality (performance → reward) · valence (value of reward)","g-ppl-motivation"],
   ["McClelland’s three needs","Achievement, affiliation, power","g-ppl-motivation"],
   ["What Title VII forbids","Discrimination by race, color, religion, sex or national origin","g-ppl-hr"],
   ["The two kinds of structured interview","Situational (what would you do) and behavioral-description (what did you do)","g-ppl-hr"],
   ["Tuckman’s five stages","Forming, storming, norming, performing, adjourning","g-ppl-groups"],
   ["Media from richest to leanest","Face-to-face · video and phone · email and personal notes · impersonal written reports","g-ppl-groups"],
   ["The five sources of power","Legitimate, reward, coercive (position) · expert, referent (personal)","g-ppl-groups"],
   ["The three classic leadership styles","Autocratic, democratic (participative), laissez-faire","g-ppl-groups"],
   ["Ways to enter a foreign market, least to most risk","Outsourcing · exporting · licensing · franchising · joint venture · wholly owned subsidiary","g-ppl-global"],
   ["Hofstede’s dimensions","Individualism–collectivism · power distance · uncertainty avoidance · masculinity–femininity · long-term orientation","g-ppl-global"],
   ["Monochronic vs polychronic","One thing at a time by the clock (US) vs many things at once by the relationship (Latin America)","g-ppl-global"]]}
 ]
};

/* ---- people questions ---- */
QB = QB.concat([
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"The three stages of Lewin’s change model, in order, are:",a:"unfreezing, changing, refreezing",w:["forming, storming, norming","planning, implementing, evaluating","analysis, design, rollout"],e:"Loosen, move, make it stick."},
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"The first stage of Lewin’s model is:",a:"unfreezing — creating the motivation to change",w:["changing — learning the new behaviors","refreezing — reinforcing the new behaviors","forming — assembling the change team"],e:"Show why the old way must go before anything else."},
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"Refreezing means:",a:"supporting and reinforcing the new behaviors so the change sticks",w:["stopping the change and returning to the old ways of working","announcing the change and explaining to everyone why it is needed","freezing all hiring until the change has been completed"],e:"Without it, people drift back."},
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"Which of these is an individual reason people resist change?",a:"Fear of the unknown and self-interest",w:["Rising interest rates in the economy","A competitor’s launch of a new product","A change in the employment law"],e:"Habit, fear, loss of status and mistrust are the personal ones; the others are forces for change."},
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"Which approach to overcoming resistance involves employees in designing the change?",a:"Participation and involvement",w:["Explicit and implicit coercion","Manipulation and co-optation","Negotiation and agreement"],e:"People support what they help build."},
 {tp:"people",sec:"g-ppl-change",t:"mc",q:"A learning organization is one that:",a:"actively creates, acquires and transfers knowledge and changes its behavior in response",w:["sends every one of its employees on a formal training course at least once in every calendar year", "hires only people who hold graduate degrees from well-known universities", "keeps the same procedures in place until the law forces it to change them"],e:"Senge’s term — it adapts continually."},
 {tp:"people",sec:"g-ppl-change",ap:true,t:"mc",q:"Before introducing a new scheduling system, a manager shows the staff how many hours the old one wastes and why it cannot continue. Which of Lewin’s stages is that?",a:"Unfreezing",w:["Changing","Refreezing","Storming"],e:"Creating the motivation to change."},
 {tp:"people",sec:"g-ppl-change",ap:true,t:"mc",q:"After moving to new software, the company rewards the teams that use it and rewrites the job descriptions to require it. Which stage is that?",a:"Refreezing",w:["Unfreezing","Changing","Forming"],e:"Making the change stick."},
 {tp:"people",sec:"g-ppl-change",t:"tf",q:"Reactive change is change made in anticipation of problems, before they arise.",a:false,e:"False — that is proactive change. Reactive change responds to a problem that has already appeared."},

 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"Motivation is best defined as:",a:"the psychological processes that arouse, direct and sustain goal-directed behavior",w:["the pay and the benefits that an employee receives in return for the work performed", "the authority a manager holds to reward or to punish the employees in the unit", "the set of rules that govern how the members of a group are expected to behave"],e:"Arouse, direct, sustain."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"In Maslow’s hierarchy, the needs from lowest to highest are:",a:"physiological, safety, love (belonging), esteem, self-actualization",w:["safety, physiological, esteem, belonging, self-actualization","achievement, affiliation, power, esteem, self-actualization","existence, relatedness, growth, esteem, self-actualization"],e:"A lower need must be met before the next one motivates."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"In Herzberg’s two-factor theory, hygiene factors:",a:"prevent dissatisfaction but do not by themselves motivate — pay, conditions, policies",w:["create satisfaction and motivation — achievement, recognition, the work itself, growth", "are the three highest needs on Maslow’s hierarchy — belonging, esteem and self-actualization", "describe how fairly employees feel they are treated compared with their colleagues"],e:"The second option describes the motivating factors."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"In expectancy theory, instrumentality is:",a:"the belief that good performance will lead to the reward",w:["the belief that effort will lead to good performance","the value that the person places on the reward offered","the comparison of one’s own rewards with another person’s"],e:"Expectancy is effort → performance; instrumentality is performance → reward; valence is the value of the reward."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"In expectancy theory, valence is:",a:"the value a person places on the reward",w:["the belief that effort will produce performance","the belief that performance will be rewarded","the number of rewards available to a team"],e:"A reward nobody wants motivates nobody."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"Goal-setting theory says the most motivating goals are:",a:"specific and challenging, with feedback on progress",w:["general and easy, so that everyone is sure to reach them","set entirely by the employee with no involvement from the manager","kept confidential until the annual performance review"],e:"“Do your best” motivates less than a specific, hard goal."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"Equity theory says people are motivated by:",a:"comparing the ratio of their outcomes to inputs with that of others",w:["the number of levels they have already climbed in Maslow’s hierarchy", "the size of the reward alone, regardless of what other people receive", "the expectancy that their own effort will lead to good performance"],e:"Fairness relative to others."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"Job enrichment means:",a:"giving a job more autonomy and responsibility — vertical loading",w:["adding more tasks at the same level — horizontal loading","moving employees between different jobs at set intervals","reducing a job to a few simple and repetitive tasks"],e:"The second option is job enlargement; the third is job rotation."},
 {tp:"people",sec:"g-ppl-motivation",t:"mc",q:"McClelland’s three acquired needs are:",a:"achievement, affiliation and power",w:["existence, relatedness and growth","safety, esteem and belonging","expectancy, instrumentality and valence"],e:"The first alternative is Alderfer’s ERG theory."},
 {tp:"people",sec:"g-ppl-motivation",ap:true,t:"mc",q:"An employee works hard but believes the promised bonus will never actually be paid. In expectancy terms, which link is broken?",a:"Instrumentality — performance does not seem to lead to the reward",w:["Expectancy — her own effort does not seem to lead to good performance", "Valence — the bonus has no value at all to this particular employee", "Equity — the bonus is smaller than the one a colleague has been promised"],e:"She can perform; she doubts the payoff."},
 {tp:"people",sec:"g-ppl-motivation",ap:true,t:"mc",q:"A call-center worker is allowed to resolve customer complaints on her own authority instead of escalating them. That is an example of:",a:"job enrichment",w:["job enlargement","job rotation","job simplification"],e:"More autonomy and responsibility — vertical loading."},
 {tp:"people",sec:"g-ppl-motivation",t:"tf",q:"According to Maslow, a higher need becomes a motivator only after the lower needs are reasonably satisfied.",a:true,e:"True."},

 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"A job description states:",a:"the tasks, duties and responsibilities of a job",w:["the qualifications a person needs to do the job","the pay and the benefits attached to the job","the number of people the job holder supervises"],e:"The second option is the job specification."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"A job specification states:",a:"the minimum qualifications a person needs to perform the job",w:["the tasks and the duties that the job involves","the manager to whom the job holder reports","the results the job holder achieved last year"],e:"What the person needs, not what the job does."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"Job analysis is:",a:"determining the basic elements of a job — what is done and what it requires",w:["the yearly evaluation of an employee’s performance against the job’s goals", "the process of interviewing the candidates who have applied for a job", "the calculation of a job’s pay grade, benefits and place on the pay scale"],e:"It produces the job description and the job specification."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"Title VII of the Civil Rights Act of 1964 prohibits employment discrimination based on:",a:"race, color, religion, sex and national origin",w:["age over forty, and nothing else","physical or mental disability, and nothing else","membership of a trade union, and nothing else"],e:"Enforced by the EEOC. Age is the ADEA; disability is the ADA."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"A behavioral-description interview asks candidates:",a:"to describe how they actually handled a situation in the past",w:["what they would do in a hypothetical future situation","general questions with no fixed structure or order","to complete a written test of their job knowledge"],e:"Past behavior predicts future behavior. The first alternative is a situational interview."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"The difference between a structured and an unstructured interview is that:",a:"a structured interview asks every candidate the same predetermined questions",w:["a structured interview is held in a formal office and an unstructured one is not","a structured interview lasts longer than an unstructured one does","a structured interview is conducted by a computer program"],e:"The same questions for everyone — fairer and more valid."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"Training differs from development in that training:",a:"teaches skills for the current job, while development prepares people for future roles",w:["is for the managers only, while development is for the hourly employees on the shop floor", "happens outside the company, while development always happens inside it", "is unpaid time for the employee, while development is paid time on the job"],e:"Now versus later."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"A 360-degree performance appraisal gathers ratings from:",a:"the employee’s manager, peers, subordinates and sometimes customers",w:["the employee’s direct manager and nobody else","an outside consultant hired for the purpose","the employee’s own self-assessment alone"],e:"All the way around."},
 {tp:"people",sec:"g-ppl-hr",t:"mc",q:"Adverse impact occurs when:",a:"an employment practice that seems neutral has a disproportionate effect on a protected group",w:["an employee is dismissed for repeated poor performance after a series of documented warnings", "a manager openly refuses to hire women for a position because of their sex", "a company’s profits fall after it freezes hiring for the rest of the year"],e:"Unintended discrimination through a practice’s results."},
 {tp:"people",sec:"g-ppl-hr",ap:true,t:"mc",q:"An interviewer asks, “Tell me about a time you had to deal with an angry customer. What did you do?” Which kind of interview question is that?",a:"Behavioral-description",w:["Situational","Unstructured","Personality test"],e:"Actual past behavior."},
 {tp:"people",sec:"g-ppl-hr",t:"tf",q:"The Equal Employment Opportunity Commission enforces Title VII.",a:true,e:"True."},
 {tp:"people",sec:"g-ppl-hr",t:"tf",q:"Quid pro quo sexual harassment refers to an offensive working atmosphere rather than a demand for favors.",a:false,e:"False — quid pro quo is favors demanded in exchange for job benefits; the atmosphere is a hostile work environment."},

 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"A team differs from a group in that a team:",a:"is a small group with complementary skills, a common purpose and mutual accountability",w:["is any two or more people who simply happen to be in the same place at the very same time", "is larger than a group and is always led by a manager appointed from above", "shares an office and a schedule but has no goals in common at all"],e:"Common purpose and mutual accountability are the marks of a team."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Tuckman’s stages of group development, in order, are:",a:"forming, storming, norming, performing, adjourning",w:["unfreezing, changing, refreezing, performing, adjourning","norming, forming, storming, performing, adjourning","planning, organizing, leading, controlling, adjourning"],e:"Conflict comes in storming; standards settle in norming."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Norms are:",a:"the general guidelines or rules of behavior that most group members follow",w:["the formal job descriptions written for each role by the human resources department", "the maximum number of people that a group is allowed to have as members", "the written contract that each member of a team signs on joining it"],e:"Unwritten, but enforced by the group."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Social loafing is:",a:"the tendency to put in less effort when working in a group than alone",w:["the tendency to socialize with colleagues instead of working when at the office", "the habit of taking long breaks during the working day when nobody is watching", "a leadership style that lets the group do as it pleases without direction"],e:"Free-riding on the group’s effort."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"In terms of media richness, the richest medium is:",a:"face-to-face conversation",w:["an email message","a memo or a letter","a flyer or a bulletin"],e:"Richness falls from face-to-face through phone and email down to impersonal written reports."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"The grapevine is:",a:"the informal, unofficial communication network of an organization",w:["the formal upward channel for employees’ complaints and suggestions", "the chain of command shown on the organization chart, from top to bottom", "the vertical channel that runs from the top of the organization to the bottom"],e:"Fast, and more accurate than people assume — around three-quarters right."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"The five sources of power identified by French and Raven are:",a:"legitimate, reward, coercive, expert and referent",w:["formal, informal, financial, technical and social","autocratic, democratic, laissez-faire, transactional and transformational","planning, organizing, leading, controlling and coordinating"],e:"The first three come with the position; expert and referent are personal."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Referent power comes from:",a:"being admired and identified with — personal charm and respect",w:["holding a formal position in the organization’s hierarchy","the ability to punish those who do not comply with orders","having specialized knowledge or skills that others need"],e:"The second is legitimate, the third coercive, the fourth expert."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"A transformational leader:",a:"inspires followers to go beyond self-interest for the organization, through vision and charisma",w:["exchanges rewards for good performance and steps in to correct any deviations from the agreed standards", "lets the group make every decision on its own, without any guidance from above", "makes every decision alone and expects the group to obey without discussion"],e:"The second option is transactional; the third laissez-faire; the fourth autocratic."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Task-oriented and relationship-oriented leadership behaviors correspond to the Ohio State dimensions of:",a:"initiating structure and consideration",w:["legitimate power and referent power","expectancy and valence","forming and norming"],e:"Structure the work; care for the people."},
 {tp:"people",sec:"g-ppl-groups",t:"mc",q:"Fiedler’s contingency model holds that:",a:"a leader’s style is relatively fixed, so the leader should be matched to a situation that fits it",w:["a leader can switch styles at will to suit each individual follower and every new situation that arises", "leaders are born with traits that guarantee success in any situation they are placed in", "the best leaders never rely on the power of their position, only on personal charm"],e:"Match the leader to the situation, not the other way round."},
 {tp:"people",sec:"g-ppl-groups",ap:true,t:"mc",q:"A manager sets clear performance targets, pays a bonus when they are met and steps in when they are missed. That is:",a:"transactional leadership",w:["transformational leadership","laissez-faire leadership","servant leadership"],e:"An exchange — rewards for performance."},
 {tp:"people",sec:"g-ppl-groups",ap:true,t:"mc",q:"Team members argue over who should lead and how the work should be divided. Which stage of development is the team in?",a:"Storming",w:["Forming","Norming","Performing"],e:"The conflict stage — before the norms settle."},
 {tp:"people",sec:"g-ppl-groups",t:"tf",q:"Expert power and referent power are forms of personal power rather than position power.",a:true,e:"True — legitimate, reward and coercive come with the position."},
 {tp:"people",sec:"g-ppl-groups",t:"tf",q:"Upward communication flows from top managers down to employees.",a:false,e:"False — that direction is downward. Messages that rise from the front line to the executives are the upward kind."},

 {tp:"people",sec:"g-ppl-global",t:"mc",q:"A tariff is:",a:"a tax on imported goods",w:["a limit on the quantity of a good that may be imported","a complete ban on trade with one particular country","a payment made to exporters by their own government"],e:"The second is an import quota; the third an embargo."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"An import quota is:",a:"a limit on the quantity of a product that may be imported",w:["a tax charged on goods as they enter the country","a ban on all trade with a single foreign country","an agreement to trade freely among member nations"],e:"Quantity, not price."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"Licensing, as a way of doing business abroad, means:",a:"a company allows a foreign firm to make or sell its product in return for a fee",w:["a company builds and fully owns a plant in the foreign country, and runs it itself", "a company shares the ownership of a new venture with a foreign partner firm", "a company sells its products abroad through independent agents based there"],e:"One Quizlet answers this with “transnational strategy” — the term is licensing."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"Franchising differs from licensing in that the franchisee:",a:"receives a complete business system — trademark, products and procedures — in return for fees",w:["takes full ownership of the parent company’s foreign plant, its staff and all of its equipment", "shares the ownership and the profits of a joint venture with the parent company abroad", "only imports the finished product from the parent company and resells it locally"],e:"A form of licensing — McDonald’s abroad."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"The most costly and riskiest way to expand abroad, and the one giving the most control, is:",a:"a wholly owned subsidiary",w:["exporting through agents","licensing a local firm","global outsourcing"],e:"You own and control everything — and carry every risk."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"A joint venture is:",a:"a business formed with a foreign partner who shares ownership, risk and profits",w:["a tax charged on goods as they enter a foreign country, collected at the border posts", "a foreign plant that the parent company fully owns, runs and controls itself", "a licence to use a foreign company’s trademark in return for a fee or a royalty"],e:"Shared ownership — also called a strategic alliance."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"In Hofstede’s framework, a culture high in individualism:",a:"expects people to look after themselves and value personal achievement",w:["expects people to accept large differences in power between the ranks of society", "prefers clear rules and avoids ambiguous or uncertain situations wherever possible", "emphasises loyalty to the group over any personal goals or achievements"],e:"The United States scores very high on it. The fourth option is collectivism."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"Power distance, in Hofstede’s terms, is:",a:"the degree to which a society accepts an unequal distribution of power",w:["the physical distance that people keep from each other during a conversation", "the degree to which people in a society avoid uncertain or ambiguous situations", "the extent to which a culture values long-term planning over the present"],e:"High power distance: bosses are bosses."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"A monochronic culture:",a:"does one thing at a time, values punctuality and keeps to a schedule",w:["does many things at once and values relationships over schedules and clocks", "relies on context and relationships rather than on words for its meaning", "accepts large gaps in power between managers and the workers below them"],e:"The United States is monochronic. One Quizlet answers “polychronic” to a one-agenda-meeting question — that is wrong."},
 {tp:"people",sec:"g-ppl-global",t:"mc",q:"A high-context culture is one where:",a:"meaning comes largely from the situation and the relationship, not just the words",w:["meaning is carried almost entirely by the explicit words that are used, not the setting", "meetings follow a single agenda and start and end exactly at the scheduled time", "people value individual achievement above the interests of the group they belong to"],e:"Japan and the Arab countries are high-context; the United States and Germany are low-context."},
 {tp:"people",sec:"g-ppl-global",ap:true,t:"mc",q:"A U.S. manager schedules a meeting with one agenda item, starts it on the minute and ends it on the minute. That behaviour reflects a:",a:"monochronic view of time",w:["polychronic view of time","high-context culture","collectivist culture"],e:"One thing at a time, by the clock."},
 {tp:"people",sec:"g-ppl-global",ap:true,t:"mc",q:"A clothing brand lets a Brazilian company make and sell its designs in Brazil in return for a percentage of sales. Which entry mode is that?",a:"Licensing",w:["A wholly owned subsidiary","A joint venture","Exporting"],e:"Rights for a fee."},
 {tp:"people",sec:"g-ppl-global",t:"tf",q:"Uncertainty avoidance describes how much a culture prefers clear rules and structured situations.",a:true,e:"True."},
 {tp:"people",sec:"g-ppl-global",t:"tf",q:"Exporting is the most expensive and riskiest way to enter a foreign market.",a:false,e:"False — exporting is among the cheapest and least risky; the wholly owned subsidiary is the most."}
]);
